// Catálogo completo de módulos e permissões do sistema.
// Use chaves estáveis no formato `modulo.recurso.acao`.

export type PermissionKey = string;

export interface PermissionDef {
  key: PermissionKey;
  label: string;
  description?: string;
}

export interface ModuleDef {
  key: string;
  label: string;
  description?: string;
  permissions: PermissionDef[];
}

export const PERMISSION_MODULES: ModuleDef[] = [
  {
    key: "dashboard",
    label: "Dashboard",
    description: "Tela inicial e indicadores gerais",
    permissions: [
      { key: "dashboard.view", label: "Ver dashboard inicial" },
      { key: "dashboard.kpis.view", label: "Ver KPIs e métricas" },
    ],
  },
  {
    key: "sdr",
    label: "SDR / Pré-venda",
    description: "Banco de leads, carteira, war room e performance",
    permissions: [
      { key: "sdr.module.view", label: "Acessar módulo SDR" },
      { key: "sdr.bank.view", label: "Ver banco de leads" },
      { key: "sdr.bank.lock", label: "Pegar lead para minha carteira" },
      { key: "sdr.bank.unlock", label: "Devolver lead ao banco" },
      { key: "sdr.bank.freeze", label: "Bloquear lead (gestor)" },
      { key: "sdr.bank.assign", label: "Atribuir lead a outro usuário" },
      { key: "sdr.wallet.view", label: "Ver minha carteira" },
      { key: "sdr.hotdeals.view", label: "Ver hot deals" },
      { key: "sdr.warroom.view", label: "Ver war room" },
      { key: "sdr.warroom.manage", label: "Gerenciar war room (gestor)" },
      { key: "sdr.performance.view", label: "Ver performance SDR" },
      { key: "sdr.performance.viewAll", label: "Ver performance de todos os SDRs" },
    ],
  },
  {
    key: "crm",
    label: "CRM",
    description: "Funil comercial e oportunidades",
    permissions: [
      { key: "crm.view", label: "Ver CRM" },
      { key: "crm.create", label: "Criar oportunidades" },
      { key: "crm.edit", label: "Editar oportunidades" },
      { key: "crm.delete", label: "Excluir oportunidades" },
      { key: "crm.viewAll", label: "Ver oportunidades de toda a equipe" },
      { key: "crm.stage.manage", label: "Configurar estágios do funil" },
    ],
  },
  {
    key: "proposals",
    label: "Propostas",
    description: "Criação, edição e envio de propostas comerciais",
    permissions: [
      { key: "proposals.view", label: "Ver propostas" },
      { key: "proposals.viewAll", label: "Ver propostas de toda a equipe" },
      { key: "proposals.create", label: "Criar propostas" },
      { key: "proposals.edit", label: "Editar propostas" },
      { key: "proposals.delete", label: "Excluir propostas" },
      { key: "proposals.send", label: "Enviar propostas ao cliente" },
      { key: "proposals.approve", label: "Aprovar propostas" },
      { key: "proposals.discount.manage", label: "Conceder descontos especiais" },
      { key: "proposals.priceTables.view", label: "Ver tabelas de preço" },
      { key: "proposals.priceTables.manage", label: "Gerenciar tabelas de preço" },
      { key: "proposals.orders.view", label: "Ver pedidos / NF" },
      { key: "proposals.orders.manage", label: "Gerenciar pedidos / NF" },
      { key: "proposals.templates.view", label: "Ver templates de proposta" },
      { key: "proposals.templates.manage", label: "Editar templates de proposta" },
    ],
  },
  {
    key: "approvals",
    label: "Aprovações",
    description: "Fila de aprovações comerciais e técnicas",
    permissions: [
      { key: "approvals.view", label: "Ver fila de aprovações" },
      { key: "approvals.act", label: "Aprovar ou reprovar" },
      { key: "approvals.reassign", label: "Redirecionar para outro aprovador" },
    ],
  },
  {
    key: "clients",
    label: "Clientes",
    description: "Cadastro e gestão de clientes",
    permissions: [
      { key: "clients.view", label: "Ver clientes" },
      { key: "clients.create", label: "Criar clientes" },
      { key: "clients.edit", label: "Editar clientes" },
      { key: "clients.delete", label: "Excluir clientes" },
      { key: "clients.export", label: "Exportar lista de clientes" },
    ],
  },
  {
    key: "equipments",
    label: "Equipamentos",
    description: "Catálogo de equipamentos e linhas",
    permissions: [
      { key: "equipments.view", label: "Ver equipamentos" },
      { key: "equipments.create", label: "Cadastrar equipamentos" },
      { key: "equipments.edit", label: "Editar equipamentos" },
      { key: "equipments.delete", label: "Excluir equipamentos" },
      { key: "equipments.import", label: "Importar catálogo" },
    ],
  },
  {
    key: "competitors",
    label: "Concorrentes",
    description: "Cadastro de concorrentes e análise competitiva",
    permissions: [
      { key: "competitors.view", label: "Ver concorrentes" },
      { key: "competitors.manage", label: "Cadastrar e editar concorrentes" },
      { key: "competitive.view", label: "Ver análise competitiva" },
    ],
  },
  {
    key: "coldpro",
    label: "ColdPro",
    description: "Projetos térmicos e simulações",
    permissions: [
      { key: "coldpro.module.view", label: "Acessar módulo ColdPro" },
      { key: "coldpro.projects.view", label: "Ver projetos" },
      { key: "coldpro.projects.create", label: "Criar projetos" },
      { key: "coldpro.projects.edit", label: "Editar projetos" },
      { key: "coldpro.projects.delete", label: "Excluir projetos" },
      { key: "coldpro.simulate", label: "Rodar simulações" },
      { key: "coldpro.catalog.view", label: "Ver catálogo técnico" },
      { key: "coldpro.catalog.manage", label: "Gerenciar catálogo técnico" },
      { key: "coldpro.products.view", label: "Ver produtos térmicos" },
      { key: "coldpro.products.manage", label: "Gerenciar produtos térmicos" },
      { key: "coldpro.reports.export", label: "Exportar relatórios técnicos" },
    ],
  },
  {
    key: "tasks",
    label: "Tarefas",
    description: "Tarefas e follow-ups",
    permissions: [
      { key: "tasks.view", label: "Ver tarefas" },
      { key: "tasks.create", label: "Criar tarefas" },
      { key: "tasks.edit", label: "Editar tarefas" },
      { key: "tasks.delete", label: "Excluir tarefas" },
      { key: "tasks.assign", label: "Atribuir tarefas a outros usuários" },
    ],
  },
  {
    key: "documents",
    label: "Documentos",
    description: "Biblioteca de documentos e anexos",
    permissions: [
      { key: "documents.view", label: "Ver documentos" },
      { key: "documents.upload", label: "Subir documentos" },
      { key: "documents.delete", label: "Excluir documentos" },
    ],
  },
  {
    key: "reports",
    label: "Relatórios",
    description: "Relatórios gerenciais e exportações",
    permissions: [
      { key: "reports.view", label: "Ver relatórios" },
      { key: "reports.export", label: "Exportar relatórios" },
      { key: "reports.financial.view", label: "Ver relatórios financeiros" },
    ],
  },
  {
    key: "nomus",
    label: "Integração Nomus",
    description: "Sincronização com o ERP Nomus",
    permissions: [
      { key: "nomus.view", label: "Ver integração Nomus" },
      { key: "nomus.sync", label: "Disparar sincronização" },
      { key: "nomus.costs.import", label: "Importar custos" },
      { key: "nomus.settings.manage", label: "Editar configurações da API Nomus" },
    ],
  },
  {
    key: "marketing",
    label: "Marketing",
    description: "Leads de marketing, kanban, carteira, remarketing e campanhas",
    permissions: [
      { key: "marketing.module.view", label: "Acessar módulo Marketing" },
      { key: "marketing.dashboard.view", label: "Ver dashboard de marketing" },
      { key: "marketing.leads.view", label: "Ver leads de marketing" },
      { key: "marketing.leads.viewAll", label: "Ver leads de todos os responsáveis" },
      { key: "marketing.leads.create", label: "Cadastrar leads manualmente" },
      { key: "marketing.leads.edit", label: "Editar leads" },
      { key: "marketing.leads.delete", label: "Excluir leads" },
      { key: "marketing.leads.assign", label: "Atribuir leads a vendedores/SDRs" },
      { key: "marketing.leads.import", label: "Importar leads em lote" },
      { key: "marketing.leads.export", label: "Exportar leads" },
      { key: "marketing.kanban.view", label: "Ver kanban de marketing" },
      { key: "marketing.kanban.manage", label: "Mover cards no kanban" },
      { key: "marketing.wallet.view", label: "Ver carteira de marketing" },
      { key: "marketing.remarketing.view", label: "Ver fila de remarketing" },
      { key: "marketing.remarketing.manage", label: "Gerenciar fila de remarketing" },
      { key: "marketing.config.view", label: "Ver configurações de marketing" },
      { key: "marketing.config.manage", label: "Editar configurações de marketing" },
      { key: "marketing.reports.view", label: "Ver relatórios de marketing" },
      { key: "marketing.reports.export", label: "Exportar relatórios de marketing" },
    ],
  },

    key: "settings",
    label: "Configurações",
    description: "Configurações gerais, usuários e permissões",
    permissions: [
      { key: "settings.view", label: "Ver configurações" },
      { key: "settings.users.view", label: "Ver lista de usuários" },
      { key: "settings.users.invite", label: "Cadastrar / convidar usuários" },
      { key: "settings.users.editRole", label: "Alterar nível de acesso de usuários" },
      { key: "settings.users.delete", label: "Remover usuários" },
      { key: "settings.permissions.manage", label: "Gerenciar permissões por módulo" },
      { key: "settings.templates.manage", label: "Editar templates de documentos" },
      { key: "settings.integrations.manage", label: "Gerenciar integrações externas" },
    ],
  },
];

export const ALL_PERMISSION_KEYS: PermissionKey[] = PERMISSION_MODULES.flatMap(
  (m) => m.permissions.map((p) => p.key),
);

export function getPermissionLabel(key: PermissionKey): string {
  for (const m of PERMISSION_MODULES) {
    const p = m.permissions.find((x) => x.key === key);
    if (p) return p.label;
  }
  return key;
}

export function getModuleOf(key: PermissionKey): ModuleDef | undefined {
  return PERMISSION_MODULES.find((m) =>
    m.permissions.some((p) => p.key === key),
  );
}

// Pacotes padrão por perfil — usados como sugestão inicial ao cadastrar usuário.
// Não substituem o que estiver salvo em role_permission_templates.
export const DEFAULT_ROLE_PACKAGES: Record<string, PermissionKey[]> = {
  sdr: [
    "dashboard.view",
    "sdr.module.view",
    "sdr.bank.view",
    "sdr.bank.lock",
    "sdr.bank.unlock",
    "sdr.wallet.view",
    "sdr.hotdeals.view",
    "sdr.warroom.view",
    "sdr.performance.view",
    "crm.view",
    "crm.create",
    "crm.edit",
    "clients.view",
    "clients.create",
    "clients.edit",
    "tasks.view",
    "tasks.create",
    "tasks.edit",
    "documents.view",
  ],
  vendedor: [
    "dashboard.view",
    "dashboard.kpis.view",
    "crm.view",
    "crm.create",
    "crm.edit",
    "proposals.view",
    "proposals.create",
    "proposals.edit",
    "proposals.send",
    "proposals.priceTables.view",
    "proposals.orders.view",
    "proposals.templates.view",
    "clients.view",
    "clients.create",
    "clients.edit",
    "equipments.view",
    "competitors.view",
    "competitive.view",
    "tasks.view",
    "tasks.create",
    "tasks.edit",
    "documents.view",
    "documents.upload",
    "reports.view",
  ],
  gerente_comercial: [
    "dashboard.view",
    "dashboard.kpis.view",
    "sdr.module.view",
    "sdr.bank.view",
    "sdr.bank.freeze",
    "sdr.bank.assign",
    "sdr.warroom.view",
    "sdr.warroom.manage",
    "sdr.performance.view",
    "sdr.performance.viewAll",
    "crm.view",
    "crm.viewAll",
    "crm.create",
    "crm.edit",
    "crm.delete",
    "crm.stage.manage",
    "proposals.view",
    "proposals.viewAll",
    "proposals.create",
    "proposals.edit",
    "proposals.send",
    "proposals.approve",
    "proposals.discount.manage",
    "proposals.priceTables.view",
    "proposals.priceTables.manage",
    "proposals.orders.view",
    "proposals.orders.manage",
    "proposals.templates.view",
    "proposals.templates.manage",
    "approvals.view",
    "approvals.act",
    "approvals.reassign",
    "clients.view",
    "clients.create",
    "clients.edit",
    "clients.delete",
    "clients.export",
    "equipments.view",
    "competitors.view",
    "competitors.manage",
    "competitive.view",
    "tasks.view",
    "tasks.create",
    "tasks.edit",
    "tasks.assign",
    "documents.view",
    "documents.upload",
    "reports.view",
    "reports.export",
    "reports.financial.view",
    "settings.view",
    "settings.users.view",
    "settings.users.invite",
    "settings.users.editRole",
    "settings.permissions.manage",
  ],
  engenharia: [
    "dashboard.view",
    "coldpro.module.view",
    "coldpro.projects.view",
    "coldpro.projects.create",
    "coldpro.projects.edit",
    "coldpro.simulate",
    "coldpro.catalog.view",
    "coldpro.catalog.manage",
    "coldpro.products.view",
    "coldpro.products.manage",
    "coldpro.reports.export",
    "equipments.view",
    "equipments.create",
    "equipments.edit",
    "tasks.view",
    "tasks.create",
    "tasks.edit",
    "documents.view",
    "documents.upload",
  ],
  orcamentista: [
    "dashboard.view",
    "proposals.view",
    "proposals.viewAll",
    "proposals.create",
    "proposals.edit",
    "proposals.priceTables.view",
    "proposals.priceTables.manage",
    "proposals.templates.view",
    "approvals.view",
    "approvals.act",
    "equipments.view",
    "clients.view",
    "tasks.view",
    "tasks.create",
    "tasks.edit",
    "documents.view",
    "documents.upload",
  ],
  diretoria: ALL_PERMISSION_KEYS,
  administrativo: [
    "dashboard.view",
    "proposals.view",
    "proposals.orders.view",
    "proposals.orders.manage",
    "clients.view",
    "documents.view",
    "documents.upload",
    "nomus.view",
    "nomus.sync",
    "nomus.costs.import",
    "reports.view",
    "reports.financial.view",
  ],
  admin: ALL_PERMISSION_KEYS,
  marketing: [
    "dashboard.view",
    "clients.view",
    "tasks.view",
    "tasks.create",
    "tasks.edit",
    "documents.view",
    "documents.upload",
    "reports.view",
  ],
};
