import * as React from "react";
export function ColdProTunnelForm({ environmentId, tunnel, onSave }: { environmentId: string; tunnel?: any; onSave: (data: any) => void }) {
  const [form, setForm] = React.useState<any>({ environment_id: environmentId, tunnel_type: "blast_freezer", operation_mode: "continuous", product_name: "Produto", product_thickness_mm: 0, product_unit_weight_kg: 0, units_per_cycle: 0, cycles_per_hour: 0, mass_kg_hour: 0, inlet_temp_c: 5, outlet_temp_c: -18, freezing_temp_c: -1.5, air_temp_c: -35, air_velocity_m_s: 3, process_time_min: 60, specific_heat_above_kcal_kg_c: 0.8, specific_heat_below_kcal_kg_c: 0.4, latent_heat_kcal_kg: 60, packaging_mass_kg_hour: 0, packaging_specific_heat_kcal_kg_c: 0.4, belt_motor_kw: 0, internal_fans_kw: 0, other_internal_kw: 0 });
  React.useEffect(() => setForm({ ...form, ...(tunnel ?? {}), environment_id: environmentId }), [environmentId, tunnel?.id]);
  const set = (key: string, value: unknown) => setForm((prev: any) => ({ ...prev, [key]: value }));
  const input = (key: string, label: string, type = "number") => <label className="space-y-1"><span className="text-xs text-muted-foreground">{label}</span><input type={type} className="w-full rounded-md border px-3 py-2 text-sm" value={form?.[key] ?? ""} onChange={(e) => set(key, type === "number" ? Number(e.target.value) : e.target.value)} /></label>;
  return <div className="rounded-2xl border bg-background p-4"><h3 className="mb-4 text-base font-semibold">Túnel de congelamento / resfriamento</h3><div className="grid grid-cols-3 gap-3">
    <label className="space-y-1"><span className="text-xs text-muted-foreground">Tipo de túnel</span><select className="w-full rounded-md border px-3 py-2 text-sm" value={form.tunnel_type} onChange={(e) => set("tunnel_type", e.target.value)}><option value="blast_freezer">Túnel de congelamento</option><option value="cooling_tunnel">Túnel de resfriamento</option></select></label>
    <label className="space-y-1"><span className="text-xs text-muted-foreground">Operação</span><select className="w-full rounded-md border px-3 py-2 text-sm" value={form.operation_mode} onChange={(e) => set("operation_mode", e.target.value)}><option value="continuous">Contínuo</option><option value="batch">Batelada</option></select></label>
    {input("product_name", "Produto", "text")}{input("product_thickness_mm", "Espessura produto (mm)")}{input("product_unit_weight_kg", "Peso unitário (kg)")}{input("units_per_cycle", "Unidades/ciclo")}{input("cycles_per_hour", "Ciclos/h")}{input("mass_kg_hour", "Massa direta kg/h")}{input("inlet_temp_c", "Temp. entrada (°C)")}{input("outlet_temp_c", "Temp. final (°C)")}{input("freezing_temp_c", "Temp. congelamento (°C)")}{input("air_temp_c", "Temp. ar (°C)")}{input("air_velocity_m_s", "Velocidade ar (m/s)")}{input("process_time_min", "Tempo processo (min)")}{input("specific_heat_above_kcal_kg_c", "Cp acima")}{input("specific_heat_below_kcal_kg_c", "Cp abaixo")}{input("latent_heat_kcal_kg", "Calor latente")}{input("packaging_mass_kg_hour", "Embalagem kg/h")}{input("packaging_specific_heat_kcal_kg_c", "Cp embalagem")}{input("belt_motor_kw", "Motor esteira (kW)")}{input("internal_fans_kw", "Ventiladores internos (kW)")}{input("other_internal_kw", "Outras cargas (kW)")}
  </div><div className="mt-4 flex justify-end"><button type="button" className="rounded-md bg-primary px-4 py-2 text-sm text-primary-foreground" onClick={() => onSave(form)}>Salvar túnel</button></div></div>;
}
