import * as React from "react";

type Props = { environmentId: string; productCatalog?: any[]; onSave: (data: any) => void };

export function ColdProProductForm({ environmentId, productCatalog = [], onSave }: Props) {
  const [form, setForm] = React.useState({ environment_id: environmentId, product_id: null as string | null, product_name: "Produto genérico", mass_kg_day: 0, mass_kg_hour: 0, inlet_temp_c: 0, outlet_temp_c: 0, process_time_h: 24, packaging_mass_kg_day: 0, packaging_specific_heat_kcal_kg_c: 0.4, specific_heat_above_kcal_kg_c: 0.8, specific_heat_below_kcal_kg_c: 0.4, latent_heat_kcal_kg: 60, initial_freezing_temp_c: -1.5 as number | null, respiration_rate_0c_w_kg: null as number | null, respiration_rate_5c_w_kg: null as number | null, respiration_rate_10c_w_kg: null as number | null, respiration_rate_15c_w_kg: null as number | null, respiration_rate_20c_w_kg: null as number | null });
  React.useEffect(() => setForm((prev) => ({ ...prev, environment_id: environmentId })), [environmentId]);
  const set = (key: string, value: unknown) => setForm((prev) => ({ ...prev, [key]: value }));
  const applyProduct = (id: string) => {
    const p = productCatalog.find((item) => item.id === id);
    if (!p) return;
    setForm((prev) => ({ ...prev, product_id: p.id, product_name: p.name, specific_heat_above_kcal_kg_c: Number(p.specific_heat_above_kcal_kg_c ?? prev.specific_heat_above_kcal_kg_c), specific_heat_below_kcal_kg_c: Number(p.specific_heat_below_kcal_kg_c ?? prev.specific_heat_below_kcal_kg_c), latent_heat_kcal_kg: Number(p.latent_heat_kcal_kg ?? prev.latent_heat_kcal_kg), initial_freezing_temp_c: p.initial_freezing_temp_c ?? prev.initial_freezing_temp_c, respiration_rate_0c_w_kg: p.respiration_rate_0c_w_kg ?? null, respiration_rate_5c_w_kg: p.respiration_rate_5c_w_kg ?? null, respiration_rate_10c_w_kg: p.respiration_rate_10c_w_kg ?? null, respiration_rate_15c_w_kg: p.respiration_rate_15c_w_kg ?? null, respiration_rate_20c_w_kg: p.respiration_rate_20c_w_kg ?? null }));
  };
  const input = (key: keyof typeof form, label: string, type = "number") => <label className="space-y-1"><span className="text-xs text-muted-foreground">{label}</span><input type={type} className="w-full rounded-md border px-3 py-2 text-sm" value={(form[key] ?? "") as any} onChange={(e) => set(key, type === "number" ? Number(e.target.value) : e.target.value)} /></label>;
  return <div className="rounded-2xl border bg-background p-4"><h3 className="mb-4 text-base font-semibold">Produto / processo</h3><label className="mb-3 block space-y-1"><span className="text-xs text-muted-foreground">Produto ASHRAE</span><select className="w-full rounded-md border bg-background px-3 py-2 text-sm" value={form.product_id ?? ""} onChange={(e) => applyProduct(e.target.value)}><option value="">Seleção manual</option>{productCatalog.map((p) => <option key={p.id} value={p.id}>{p.name} · {p.category ?? "Catálogo"}</option>)}</select></label><div className="grid grid-cols-3 gap-3">{input("product_name", "Produto", "text")}{input("mass_kg_day", "Massa diária (kg/dia)")}{input("mass_kg_hour", "Massa horária (kg/h)")}{input("inlet_temp_c", "Temp. entrada (°C)")}{input("outlet_temp_c", "Temp. final (°C)")}{input("process_time_h", "Tempo processo (h)")}{input("specific_heat_above_kcal_kg_c", "Calor específico acima")}{input("specific_heat_below_kcal_kg_c", "Calor específico abaixo")}{input("latent_heat_kcal_kg", "Calor latente")}{input("initial_freezing_temp_c", "Temp. congelamento")}{input("packaging_mass_kg_day", "Embalagem kg/dia")}{input("packaging_specific_heat_kcal_kg_c", "Cp embalagem")}</div><div className="mt-3 text-xs text-muted-foreground">Dados ASHRAE são convertidos para kcal/kg·°C e kcal/kg. Produtos frescos carregam respiração automaticamente.</div><div className="mt-4 flex justify-end"><button type="button" className="rounded-md bg-primary px-4 py-2 text-sm text-primary-foreground" onClick={() => onSave(form)}>Salvar produto</button></div></div>;
}
