import * as React from "react";

type Props = { environmentId: string; productCatalog?: any[]; onSave: (data: any) => void };

export function ColdProProductForm({ environmentId, productCatalog = [], onSave }: Props) {
  const [selectedGroup, setSelectedGroup] = React.useState("");
  const [form, setForm] = React.useState({ environment_id: environmentId, product_id: null as string | null, product_name: "Produto genérico", mass_kg_day: 0, mass_kg_hour: 0, inlet_temp_c: 0, outlet_temp_c: 0, process_time_h: 24, packaging_mass_kg_day: 0, packaging_specific_heat_kcal_kg_c: 0.4, specific_heat_above_kcal_kg_c: 0.8, specific_heat_below_kcal_kg_c: 0.4, latent_heat_kcal_kg: 60, initial_freezing_temp_c: -1.5 as number | null, density_kg_m3: null as number | null, thermal_conductivity_unfrozen_w_m_k: null as number | null, thermal_conductivity_frozen_w_m_k: null as number | null, frozen_water_fraction: null as number | null, freezable_water_content_percent: null as number | null, characteristic_thickness_m: null as number | null, default_convective_coefficient_w_m2_k: null as number | null, allow_phase_change: true as boolean | null, respiration_rate_0c_w_kg: null as number | null, respiration_rate_5c_w_kg: null as number | null, respiration_rate_10c_w_kg: null as number | null, respiration_rate_15c_w_kg: null as number | null, respiration_rate_20c_w_kg: null as number | null });
  React.useEffect(() => setForm((prev) => ({ ...prev, environment_id: environmentId })), [environmentId]);
  const set = (key: string, value: unknown) => setForm((prev) => ({ ...prev, [key]: value }));
  const groups = React.useMemo(() => Array.from(new Set(productCatalog.map((p) => p.category).filter(Boolean))).sort((a, b) => String(a).localeCompare(String(b), "pt-BR")), [productCatalog]);
  const filteredProducts = React.useMemo(() => productCatalog.filter((p) => !selectedGroup || p.category === selectedGroup), [productCatalog, selectedGroup]);
  const applyGroup = (group: string) => {
    setSelectedGroup(group);
    setForm((prev) => ({ ...prev, product_id: null, product_name: group ? "" : "Produto genérico" }));
  };
  const applyProduct = (id: string) => {
    const p = productCatalog.find((item) => item.id === id);
    if (!p) return;
    setForm((prev) => ({ ...prev, product_id: p.id, product_name: p.name, specific_heat_above_kcal_kg_c: Number(p.specific_heat_above_kcal_kg_c ?? prev.specific_heat_above_kcal_kg_c), specific_heat_below_kcal_kg_c: Number(p.specific_heat_below_kcal_kg_c ?? prev.specific_heat_below_kcal_kg_c), latent_heat_kcal_kg: Number(p.latent_heat_kcal_kg ?? prev.latent_heat_kcal_kg), initial_freezing_temp_c: p.initial_freezing_temp_c ?? prev.initial_freezing_temp_c, density_kg_m3: p.density_kg_m3 ?? null, thermal_conductivity_unfrozen_w_m_k: p.thermal_conductivity_unfrozen_w_m_k ?? p.thermal_conductivity_w_m_k ?? null, thermal_conductivity_frozen_w_m_k: p.thermal_conductivity_frozen_w_m_k ?? null, frozen_water_fraction: p.frozen_water_fraction ?? null, freezable_water_content_percent: p.freezable_water_content_percent ?? null, characteristic_thickness_m: p.characteristic_thickness_m ?? null, default_convective_coefficient_w_m2_k: p.default_convective_coefficient_w_m2_k ?? null, allow_phase_change: p.allow_phase_change ?? true, respiration_rate_0c_w_kg: p.respiration_rate_0c_w_kg ?? null, respiration_rate_5c_w_kg: p.respiration_rate_5c_w_kg ?? null, respiration_rate_10c_w_kg: p.respiration_rate_10c_w_kg ?? null, respiration_rate_15c_w_kg: p.respiration_rate_15c_w_kg ?? null, respiration_rate_20c_w_kg: p.respiration_rate_20c_w_kg ?? null }));
  };
  const input = (key: keyof typeof form, label: string, type = "number") => <label className="space-y-1"><span className="text-xs text-muted-foreground">{label}</span><input type={type} className="w-full rounded-md border px-3 py-2 text-sm" value={(form[key] ?? "") as any} onChange={(e) => set(key, type === "number" ? Number(e.target.value) : e.target.value)} /></label>;
  return <div className="rounded-2xl border bg-background p-4"><h3 className="mb-4 text-base font-semibold">Produto / processo</h3><div className="mb-3 grid gap-3 md:grid-cols-2"><label className="block space-y-1"><span className="text-xs text-muted-foreground">Grupo ASHRAE</span><select className="w-full rounded-md border bg-background px-3 py-2 text-sm" value={selectedGroup} onChange={(e) => applyGroup(e.target.value)}><option value="">Seleção manual</option>{groups.map((group) => <option key={group} value={group}>{group}</option>)}</select></label><label className="block space-y-1"><span className="text-xs text-muted-foreground">Produto</span><select className="w-full rounded-md border bg-background px-3 py-2 text-sm disabled:opacity-60" value={form.product_id ?? ""} disabled={!selectedGroup} onChange={(e) => applyProduct(e.target.value)}><option value="">{selectedGroup ? "Selecione o produto" : "Selecione primeiro o grupo"}</option>{filteredProducts.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div><div className="grid grid-cols-3 gap-3">{input("product_name", "Produto", "text")}{input("mass_kg_day", "Movimentação diária (kg/dia)")}{input("mass_kg_hour", "Movimentação horária (kg/h)")}{input("inlet_temp_c", "Temp. entrada produto (°C)")}{input("outlet_temp_c", "Temp. final produto (°C)")}{input("process_time_h", "Tempo processo (h)")}{input("specific_heat_above_kcal_kg_c", "Cp acima")}{input("specific_heat_below_kcal_kg_c", "Cp abaixo")}{input("latent_heat_kcal_kg", "Calor latente")}{input("initial_freezing_temp_c", "Temp. congelamento")}{input("packaging_mass_kg_day", "Embalagem kg/dia")}{input("packaging_specific_heat_kcal_kg_c", "Cp embalagem")}{input("density_kg_m3", "Densidade produto")}{input("thermal_conductivity_frozen_w_m_k", "Condutividade congelado")}{input("frozen_water_fraction", "Fração água congelável")}</div><div className="mt-3 text-xs text-muted-foreground">Esta aba concentra produto, movimentação, temperaturas do produto, embalagem e propriedades térmicas ASHRAE.</div><div className="mt-4 flex justify-end"><button type="button" className="rounded-md bg-primary px-4 py-2 text-sm text-primary-foreground" onClick={() => onSave(form)}>Salvar produto</button></div></div>;
}
