export type TunnelProcessStatus = "missing_data" | "invalid_input" | "adequate" | "insufficient";
export type ConvectiveCoefficientSource = "manual" | "velocity" | "missing";
export type ThermalUnitSource = "kJ" | "kcal_converted" | "missing";

export interface TunnelCalculationInput {
  processType?: string | null;
  operationMode?: string | null;
  unitWeightKg?: number | null;
  unitsPerCycle?: number | null;
  cyclesPerHour?: number | null;
  directMassKgH?: number | null;
  staticMassKg?: number | null;
  batchTimeH?: number | null;
  retentionTimeMin?: number | null;
  productLengthM?: number | null;
  productWidthM?: number | null;
  productThicknessM?: number | null;
  palletLengthM?: number | null;
  palletWidthM?: number | null;
  palletHeightM?: number | null;
  airTempSource?: "environment" | "manual" | string | null;
  airTempC?: number | null;
  airVelocityMS?: number | null;
  manualConvectiveCoefficientWM2K?: number | null;
  convective_coefficient_manual_w_m2_k?: number | null;
  airDeltaTK?: number | null;
  airDensityKgM3?: number | null;
  airExposureFactor?: number | null;
  thermalPenetrationFactor?: number | null;
  initialTempC?: number | null;
  finalTempC?: number | null;
  freezingPointC?: number | null;
  cpAboveKJkgK?: number | null;
  cpBelowKJkgK?: number | null;
  latentHeatKJkg?: number | null;
  frozenWaterFraction?: number | null;
  frozenConductivityWMK?: number | null;
  densityKgM3?: number | null;
  packagingMassKgH?: number | null;
  packagingCpKJkgK?: number | null;
  beltMotorKW?: number | null;
  internalFansKW?: number | null;
  otherInternalKW?: number | null;
  allowPhaseChange?: boolean | null;
  originalInput?: Record<string, unknown>;
  unitConversions?: Record<string, unknown>;
}

export interface TunnelEngineResult {
  processType: string;
  isStatic: boolean;
  calculatedMassKgH: number;
  usedMassKgH: number;
  staticMassKg: number;
  characteristicDimensionM: number | null;
  distanceToCoreM: number | null;
  energy: Record<string, number | boolean>;
  h: { hBaseWM2K: number | null; hEffectiveWM2K: number | null; source: ConvectiveCoefficientSource };
  kEffectiveWMK: number | null;
  estimatedTimeMin: number | null;
  availableTimeMin: number | null;
  status: TunnelProcessStatus;
  productLoadKW: number;
  packagingLoadKW: number;
  internalLoadKW: number;
  totalKW: number;
  totalKcalH: number;
  totalTR: number;
  missingFields: string[];
  warnings: string[];
  calculationBreakdown: Record<string, unknown>;
  calculationLog: Record<string, unknown>;
}
