/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTarefasRouteImport } from './routes/app.tarefas'
import { Route as AppRelatoriosRouteImport } from './routes/app.relatorios'
import { Route as AppProdutividadeRouteImport } from './routes/app.produtividade'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppGestaoRouteImport } from './routes/app.gestao'
import { Route as AppEquipamentosRouteImport } from './routes/app.equipamentos'
import { Route as AppDocumentosRouteImport } from './routes/app.documentos'
import { Route as AppDashboardGeralRouteImport } from './routes/app.dashboard-geral'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppConcorrentesRouteImport } from './routes/app.concorrentes'
import { Route as AppCompetitivaRouteImport } from './routes/app.competitiva'
import { Route as AppCoberturaRouteImport } from './routes/app.cobertura'
import { Route as AppClientesRouteImport } from './routes/app.clientes'
import { Route as AppAtividadesRouteImport } from './routes/app.atividades'
import { Route as AppAprovacoesRouteImport } from './routes/app.aprovacoes'
import { Route as AppAgendaRouteImport } from './routes/app.agenda'
import { Route as AppSdrIndexRouteImport } from './routes/app.sdr.index'
import { Route as AppPropostasIndexRouteImport } from './routes/app.propostas.index'
import { Route as AppCrmIndexRouteImport } from './routes/app.crm.index'
import { Route as AppConfiguracoesIndexRouteImport } from './routes/app.configuracoes.index'
import { Route as AppColdproIndexRouteImport } from './routes/app.coldpro.index'
import { Route as AppVendasCarteiraRouteImport } from './routes/app.vendas.carteira'
import { Route as AppSdrWarRoomRouteImport } from './routes/app.sdr.war-room'
import { Route as AppSdrWalletRouteImport } from './routes/app.sdr.wallet'
import { Route as AppSdrSdrPerformanceRouteImport } from './routes/app.sdr.sdr-performance'
import { Route as AppSdrScriptsRouteImport } from './routes/app.sdr.scripts'
import { Route as AppSdrRelatoriosRouteImport } from './routes/app.sdr.relatorios'
import { Route as AppSdrHotDealsRouteImport } from './routes/app.sdr.hot-deals'
import { Route as AppSdrBankRouteImport } from './routes/app.sdr.bank'
import { Route as AppPropostasTabelasPrecoRouteImport } from './routes/app.propostas.tabelas-preco'
import { Route as AppPropostasPedidosNfRouteImport } from './routes/app.propostas.pedidos-nf'
import { Route as AppPropostasNovaRouteImport } from './routes/app.propostas.nova'
import { Route as AppPropostasIdRouteImport } from './routes/app.propostas.$id'
import { Route as AppGestaoAuditoriaSdrRouteImport } from './routes/app.gestao.auditoria-sdr'
import { Route as AppGestaoAtividadesRouteImport } from './routes/app.gestao.atividades'
import { Route as AppGestaoAlertasSdrRouteImport } from './routes/app.gestao.alertas-sdr'
import { Route as AppCrmClosersPerformanceRouteImport } from './routes/app.crm.closers-performance'
import { Route as AppCrmIdRouteImport } from './routes/app.crm.$id'
import { Route as AppConfiguracoesPermissoesRouteImport } from './routes/app.configuracoes.permissoes'
import { Route as AppConfiguracoesNomusRouteImport } from './routes/app.configuracoes.nomus'
import { Route as AppConfiguracoesApiNomusRouteImport } from './routes/app.configuracoes.api-nomus'
import { Route as AppColdproProdutosRouteImport } from './routes/app.coldpro.produtos'
import { Route as AppColdproCatalogoRouteImport } from './routes/app.coldpro.catalogo'
import { Route as AppColdproIdRouteImport } from './routes/app.coldpro.$id'
import { Route as AppAgendaIdRouteImport } from './routes/app.agenda.$id'
import { Route as AppAdminUsuariosRouteImport } from './routes/app.admin.usuarios'
import { Route as ApiNomusTestRouteImport } from './routes/api.nomus.test'
import { Route as AppPropostasIdIndexRouteImport } from './routes/app.propostas.$id.index'
import { Route as AppGestaoCarteirasIndexRouteImport } from './routes/app.gestao.carteiras.index'
import { Route as AppConfiguracoesTemplatesIndexRouteImport } from './routes/app.configuracoes.templates.index'
import { Route as AppSdrLeadsIdRouteImport } from './routes/app.sdr.leads.$id'
import { Route as AppPropostasIdEditorRouteImport } from './routes/app.propostas.$id.editor'
import { Route as AppGestaoCarteirasUserIdRouteImport } from './routes/app.gestao.carteiras.$userId'
import { Route as AppConfiguracoesTemplatesIdRouteImport } from './routes/app.configuracoes.templates.$id'
import { Route as AppConfiguracoesNomusImportarCustosRouteImport } from './routes/app.configuracoes.nomus.importar-custos'
import { Route as ApiPublicNomusTabelaPrecoProbeRouteImport } from './routes/api.public.nomus.tabela-preco-probe'
import { Route as ApiPublicNomusTabelaPrecoDeepProbeRouteImport } from './routes/api.public.nomus.tabela-preco-deep-probe'
import { Route as ApiPublicNomusProdutoProbeRouteImport } from './routes/api.public.nomus.produto-probe'
import { Route as ApiPublicNomusExhaustiveProbeRouteImport } from './routes/api.public.nomus.exhaustive-probe'
import { Route as ApiPublicLeadsSiteRouteImport } from './routes/api.public.leads.site'
import { Route as ApiPublicHooksNomusCronRouteImport } from './routes/api.public.hooks.nomus-cron'
import { Route as AuthenticatedAppSdrNovoLeadRouteImport } from './routes/_authenticated.app.sdr.novo-lead'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTarefasRoute = AppTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutividadeRoute = AppProdutividadeRouteImport.update({
  id: '/produtividade',
  path: '/produtividade',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppGestaoRoute = AppGestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipamentosRoute = AppEquipamentosRouteImport.update({
  id: '/equipamentos',
  path: '/equipamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentosRoute = AppDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardGeralRoute = AppDashboardGeralRouteImport.update({
  id: '/dashboard-geral',
  path: '/dashboard-geral',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppConcorrentesRoute = AppConcorrentesRouteImport.update({
  id: '/concorrentes',
  path: '/concorrentes',
  getParentRoute: () => AppRoute,
} as any)
const AppCompetitivaRoute = AppCompetitivaRouteImport.update({
  id: '/competitiva',
  path: '/competitiva',
  getParentRoute: () => AppRoute,
} as any)
const AppCoberturaRoute = AppCoberturaRouteImport.update({
  id: '/cobertura',
  path: '/cobertura',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppAtividadesRoute = AppAtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => AppRoute,
} as any)
const AppAprovacoesRoute = AppAprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppSdrIndexRoute = AppSdrIndexRouteImport.update({
  id: '/sdr/',
  path: '/sdr/',
  getParentRoute: () => AppRoute,
} as any)
const AppPropostasIndexRoute = AppPropostasIndexRouteImport.update({
  id: '/propostas/',
  path: '/propostas/',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmIndexRoute = AppCrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesIndexRoute = AppConfiguracoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppConfiguracoesRoute,
} as any)
const AppColdproIndexRoute = AppColdproIndexRouteImport.update({
  id: '/coldpro/',
  path: '/coldpro/',
  getParentRoute: () => AppRoute,
} as any)
const AppVendasCarteiraRoute = AppVendasCarteiraRouteImport.update({
  id: '/vendas/carteira',
  path: '/vendas/carteira',
  getParentRoute: () => AppRoute,
} as any)
const AppSdrWarRoomRoute = AppSdrWarRoomRouteImport.update({
  id: '/sdr/war-room',
  path: '/sdr/war-room',
  getParentRoute: () => AppRoute,
} as any)
const AppSdrWalletRoute = AppSdrWalletRouteImport.update({
  id: '/sdr/wallet',
  path: '/sdr/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppSdrSdrPerformanceRoute = AppSdrSdrPerformanceRouteImport.update({
  id: '/sdr/sdr-performance',
  path: '/sdr/sdr-performance',
  getParentRoute: () => AppRoute,
} as any)
const AppSdrScriptsRoute = AppSdrScriptsRouteImport.update({
  id: '/sdr/scripts',
  path: '/sdr/scripts',
  getParentRoute: () => AppRoute,
} as any)
const AppSdrRelatoriosRoute = AppSdrRelatoriosRouteImport.update({
  id: '/sdr/relatorios',
  path: '/sdr/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppSdrHotDealsRoute = AppSdrHotDealsRouteImport.update({
  id: '/sdr/hot-deals',
  path: '/sdr/hot-deals',
  getParentRoute: () => AppRoute,
} as any)
const AppSdrBankRoute = AppSdrBankRouteImport.update({
  id: '/sdr/bank',
  path: '/sdr/bank',
  getParentRoute: () => AppRoute,
} as any)
const AppPropostasTabelasPrecoRoute =
  AppPropostasTabelasPrecoRouteImport.update({
    id: '/propostas/tabelas-preco',
    path: '/propostas/tabelas-preco',
    getParentRoute: () => AppRoute,
  } as any)
const AppPropostasPedidosNfRoute = AppPropostasPedidosNfRouteImport.update({
  id: '/propostas/pedidos-nf',
  path: '/propostas/pedidos-nf',
  getParentRoute: () => AppRoute,
} as any)
const AppPropostasNovaRoute = AppPropostasNovaRouteImport.update({
  id: '/propostas/nova',
  path: '/propostas/nova',
  getParentRoute: () => AppRoute,
} as any)
const AppPropostasIdRoute = AppPropostasIdRouteImport.update({
  id: '/propostas/$id',
  path: '/propostas/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppGestaoAuditoriaSdrRoute = AppGestaoAuditoriaSdrRouteImport.update({
  id: '/auditoria-sdr',
  path: '/auditoria-sdr',
  getParentRoute: () => AppGestaoRoute,
} as any)
const AppGestaoAtividadesRoute = AppGestaoAtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => AppGestaoRoute,
} as any)
const AppGestaoAlertasSdrRoute = AppGestaoAlertasSdrRouteImport.update({
  id: '/alertas-sdr',
  path: '/alertas-sdr',
  getParentRoute: () => AppGestaoRoute,
} as any)
const AppCrmClosersPerformanceRoute =
  AppCrmClosersPerformanceRouteImport.update({
    id: '/crm/closers-performance',
    path: '/crm/closers-performance',
    getParentRoute: () => AppRoute,
  } as any)
const AppCrmIdRoute = AppCrmIdRouteImport.update({
  id: '/crm/$id',
  path: '/crm/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesPermissoesRoute =
  AppConfiguracoesPermissoesRouteImport.update({
    id: '/permissoes',
    path: '/permissoes',
    getParentRoute: () => AppConfiguracoesRoute,
  } as any)
const AppConfiguracoesNomusRoute = AppConfiguracoesNomusRouteImport.update({
  id: '/nomus',
  path: '/nomus',
  getParentRoute: () => AppConfiguracoesRoute,
} as any)
const AppConfiguracoesApiNomusRoute =
  AppConfiguracoesApiNomusRouteImport.update({
    id: '/api-nomus',
    path: '/api-nomus',
    getParentRoute: () => AppConfiguracoesRoute,
  } as any)
const AppColdproProdutosRoute = AppColdproProdutosRouteImport.update({
  id: '/coldpro/produtos',
  path: '/coldpro/produtos',
  getParentRoute: () => AppRoute,
} as any)
const AppColdproCatalogoRoute = AppColdproCatalogoRouteImport.update({
  id: '/coldpro/catalogo',
  path: '/coldpro/catalogo',
  getParentRoute: () => AppRoute,
} as any)
const AppColdproIdRoute = AppColdproIdRouteImport.update({
  id: '/coldpro/$id',
  path: '/coldpro/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaIdRoute = AppAgendaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAgendaRoute,
} as any)
const AppAdminUsuariosRoute = AppAdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const ApiNomusTestRoute = ApiNomusTestRouteImport.update({
  id: '/api/nomus/test',
  path: '/api/nomus/test',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPropostasIdIndexRoute = AppPropostasIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPropostasIdRoute,
} as any)
const AppGestaoCarteirasIndexRoute = AppGestaoCarteirasIndexRouteImport.update({
  id: '/carteiras/',
  path: '/carteiras/',
  getParentRoute: () => AppGestaoRoute,
} as any)
const AppConfiguracoesTemplatesIndexRoute =
  AppConfiguracoesTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AppConfiguracoesRoute,
  } as any)
const AppSdrLeadsIdRoute = AppSdrLeadsIdRouteImport.update({
  id: '/sdr/leads/$id',
  path: '/sdr/leads/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPropostasIdEditorRoute = AppPropostasIdEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AppPropostasIdRoute,
} as any)
const AppGestaoCarteirasUserIdRoute =
  AppGestaoCarteirasUserIdRouteImport.update({
    id: '/carteiras/$userId',
    path: '/carteiras/$userId',
    getParentRoute: () => AppGestaoRoute,
  } as any)
const AppConfiguracoesTemplatesIdRoute =
  AppConfiguracoesTemplatesIdRouteImport.update({
    id: '/templates/$id',
    path: '/templates/$id',
    getParentRoute: () => AppConfiguracoesRoute,
  } as any)
const AppConfiguracoesNomusImportarCustosRoute =
  AppConfiguracoesNomusImportarCustosRouteImport.update({
    id: '/importar-custos',
    path: '/importar-custos',
    getParentRoute: () => AppConfiguracoesNomusRoute,
  } as any)
const ApiPublicNomusTabelaPrecoProbeRoute =
  ApiPublicNomusTabelaPrecoProbeRouteImport.update({
    id: '/api/public/nomus/tabela-preco-probe',
    path: '/api/public/nomus/tabela-preco-probe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNomusTabelaPrecoDeepProbeRoute =
  ApiPublicNomusTabelaPrecoDeepProbeRouteImport.update({
    id: '/api/public/nomus/tabela-preco-deep-probe',
    path: '/api/public/nomus/tabela-preco-deep-probe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNomusProdutoProbeRoute =
  ApiPublicNomusProdutoProbeRouteImport.update({
    id: '/api/public/nomus/produto-probe',
    path: '/api/public/nomus/produto-probe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNomusExhaustiveProbeRoute =
  ApiPublicNomusExhaustiveProbeRouteImport.update({
    id: '/api/public/nomus/exhaustive-probe',
    path: '/api/public/nomus/exhaustive-probe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLeadsSiteRoute = ApiPublicLeadsSiteRouteImport.update({
  id: '/api/public/leads/site',
  path: '/api/public/leads/site',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksNomusCronRoute = ApiPublicHooksNomusCronRouteImport.update({
  id: '/api/public/hooks/nomus-cron',
  path: '/api/public/hooks/nomus-cron',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppSdrNovoLeadRoute =
  AuthenticatedAppSdrNovoLeadRouteImport.update({
    id: '/app/sdr/novo-lead',
    path: '/app/sdr/novo-lead',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/agenda': typeof AppAgendaRouteWithChildren
  '/app/aprovacoes': typeof AppAprovacoesRoute
  '/app/atividades': typeof AppAtividadesRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/cobertura': typeof AppCoberturaRoute
  '/app/competitiva': typeof AppCompetitivaRoute
  '/app/concorrentes': typeof AppConcorrentesRoute
  '/app/configuracoes': typeof AppConfiguracoesRouteWithChildren
  '/app/dashboard-geral': typeof AppDashboardGeralRoute
  '/app/documentos': typeof AppDocumentosRoute
  '/app/equipamentos': typeof AppEquipamentosRoute
  '/app/gestao': typeof AppGestaoRouteWithChildren
  '/app/perfil': typeof AppPerfilRoute
  '/app/produtividade': typeof AppProdutividadeRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/tarefas': typeof AppTarefasRoute
  '/app/': typeof AppIndexRoute
  '/api/nomus/test': typeof ApiNomusTestRoute
  '/app/admin/usuarios': typeof AppAdminUsuariosRoute
  '/app/agenda/$id': typeof AppAgendaIdRoute
  '/app/coldpro/$id': typeof AppColdproIdRoute
  '/app/coldpro/catalogo': typeof AppColdproCatalogoRoute
  '/app/coldpro/produtos': typeof AppColdproProdutosRoute
  '/app/configuracoes/api-nomus': typeof AppConfiguracoesApiNomusRoute
  '/app/configuracoes/nomus': typeof AppConfiguracoesNomusRouteWithChildren
  '/app/configuracoes/permissoes': typeof AppConfiguracoesPermissoesRoute
  '/app/crm/$id': typeof AppCrmIdRoute
  '/app/crm/closers-performance': typeof AppCrmClosersPerformanceRoute
  '/app/gestao/alertas-sdr': typeof AppGestaoAlertasSdrRoute
  '/app/gestao/atividades': typeof AppGestaoAtividadesRoute
  '/app/gestao/auditoria-sdr': typeof AppGestaoAuditoriaSdrRoute
  '/app/propostas/$id': typeof AppPropostasIdRouteWithChildren
  '/app/propostas/nova': typeof AppPropostasNovaRoute
  '/app/propostas/pedidos-nf': typeof AppPropostasPedidosNfRoute
  '/app/propostas/tabelas-preco': typeof AppPropostasTabelasPrecoRoute
  '/app/sdr/bank': typeof AppSdrBankRoute
  '/app/sdr/hot-deals': typeof AppSdrHotDealsRoute
  '/app/sdr/relatorios': typeof AppSdrRelatoriosRoute
  '/app/sdr/scripts': typeof AppSdrScriptsRoute
  '/app/sdr/sdr-performance': typeof AppSdrSdrPerformanceRoute
  '/app/sdr/wallet': typeof AppSdrWalletRoute
  '/app/sdr/war-room': typeof AppSdrWarRoomRoute
  '/app/vendas/carteira': typeof AppVendasCarteiraRoute
  '/app/coldpro/': typeof AppColdproIndexRoute
  '/app/configuracoes/': typeof AppConfiguracoesIndexRoute
  '/app/crm/': typeof AppCrmIndexRoute
  '/app/propostas/': typeof AppPropostasIndexRoute
  '/app/sdr/': typeof AppSdrIndexRoute
  '/app/sdr/novo-lead': typeof AuthenticatedAppSdrNovoLeadRoute
  '/api/public/hooks/nomus-cron': typeof ApiPublicHooksNomusCronRoute
  '/api/public/leads/site': typeof ApiPublicLeadsSiteRoute
  '/api/public/nomus/exhaustive-probe': typeof ApiPublicNomusExhaustiveProbeRoute
  '/api/public/nomus/produto-probe': typeof ApiPublicNomusProdutoProbeRoute
  '/api/public/nomus/tabela-preco-deep-probe': typeof ApiPublicNomusTabelaPrecoDeepProbeRoute
  '/api/public/nomus/tabela-preco-probe': typeof ApiPublicNomusTabelaPrecoProbeRoute
  '/app/configuracoes/nomus/importar-custos': typeof AppConfiguracoesNomusImportarCustosRoute
  '/app/configuracoes/templates/$id': typeof AppConfiguracoesTemplatesIdRoute
  '/app/gestao/carteiras/$userId': typeof AppGestaoCarteirasUserIdRoute
  '/app/propostas/$id/editor': typeof AppPropostasIdEditorRoute
  '/app/sdr/leads/$id': typeof AppSdrLeadsIdRoute
  '/app/configuracoes/templates/': typeof AppConfiguracoesTemplatesIndexRoute
  '/app/gestao/carteiras/': typeof AppGestaoCarteirasIndexRoute
  '/app/propostas/$id/': typeof AppPropostasIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/agenda': typeof AppAgendaRouteWithChildren
  '/app/aprovacoes': typeof AppAprovacoesRoute
  '/app/atividades': typeof AppAtividadesRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/cobertura': typeof AppCoberturaRoute
  '/app/competitiva': typeof AppCompetitivaRoute
  '/app/concorrentes': typeof AppConcorrentesRoute
  '/app/dashboard-geral': typeof AppDashboardGeralRoute
  '/app/documentos': typeof AppDocumentosRoute
  '/app/equipamentos': typeof AppEquipamentosRoute
  '/app/gestao': typeof AppGestaoRouteWithChildren
  '/app/perfil': typeof AppPerfilRoute
  '/app/produtividade': typeof AppProdutividadeRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/tarefas': typeof AppTarefasRoute
  '/app': typeof AppIndexRoute
  '/api/nomus/test': typeof ApiNomusTestRoute
  '/app/admin/usuarios': typeof AppAdminUsuariosRoute
  '/app/agenda/$id': typeof AppAgendaIdRoute
  '/app/coldpro/$id': typeof AppColdproIdRoute
  '/app/coldpro/catalogo': typeof AppColdproCatalogoRoute
  '/app/coldpro/produtos': typeof AppColdproProdutosRoute
  '/app/configuracoes/api-nomus': typeof AppConfiguracoesApiNomusRoute
  '/app/configuracoes/nomus': typeof AppConfiguracoesNomusRouteWithChildren
  '/app/configuracoes/permissoes': typeof AppConfiguracoesPermissoesRoute
  '/app/crm/$id': typeof AppCrmIdRoute
  '/app/crm/closers-performance': typeof AppCrmClosersPerformanceRoute
  '/app/gestao/alertas-sdr': typeof AppGestaoAlertasSdrRoute
  '/app/gestao/atividades': typeof AppGestaoAtividadesRoute
  '/app/gestao/auditoria-sdr': typeof AppGestaoAuditoriaSdrRoute
  '/app/propostas/nova': typeof AppPropostasNovaRoute
  '/app/propostas/pedidos-nf': typeof AppPropostasPedidosNfRoute
  '/app/propostas/tabelas-preco': typeof AppPropostasTabelasPrecoRoute
  '/app/sdr/bank': typeof AppSdrBankRoute
  '/app/sdr/hot-deals': typeof AppSdrHotDealsRoute
  '/app/sdr/relatorios': typeof AppSdrRelatoriosRoute
  '/app/sdr/scripts': typeof AppSdrScriptsRoute
  '/app/sdr/sdr-performance': typeof AppSdrSdrPerformanceRoute
  '/app/sdr/wallet': typeof AppSdrWalletRoute
  '/app/sdr/war-room': typeof AppSdrWarRoomRoute
  '/app/vendas/carteira': typeof AppVendasCarteiraRoute
  '/app/coldpro': typeof AppColdproIndexRoute
  '/app/configuracoes': typeof AppConfiguracoesIndexRoute
  '/app/crm': typeof AppCrmIndexRoute
  '/app/propostas': typeof AppPropostasIndexRoute
  '/app/sdr': typeof AppSdrIndexRoute
  '/app/sdr/novo-lead': typeof AuthenticatedAppSdrNovoLeadRoute
  '/api/public/hooks/nomus-cron': typeof ApiPublicHooksNomusCronRoute
  '/api/public/leads/site': typeof ApiPublicLeadsSiteRoute
  '/api/public/nomus/exhaustive-probe': typeof ApiPublicNomusExhaustiveProbeRoute
  '/api/public/nomus/produto-probe': typeof ApiPublicNomusProdutoProbeRoute
  '/api/public/nomus/tabela-preco-deep-probe': typeof ApiPublicNomusTabelaPrecoDeepProbeRoute
  '/api/public/nomus/tabela-preco-probe': typeof ApiPublicNomusTabelaPrecoProbeRoute
  '/app/configuracoes/nomus/importar-custos': typeof AppConfiguracoesNomusImportarCustosRoute
  '/app/configuracoes/templates/$id': typeof AppConfiguracoesTemplatesIdRoute
  '/app/gestao/carteiras/$userId': typeof AppGestaoCarteirasUserIdRoute
  '/app/propostas/$id/editor': typeof AppPropostasIdEditorRoute
  '/app/sdr/leads/$id': typeof AppSdrLeadsIdRoute
  '/app/configuracoes/templates': typeof AppConfiguracoesTemplatesIndexRoute
  '/app/gestao/carteiras': typeof AppGestaoCarteirasIndexRoute
  '/app/propostas/$id': typeof AppPropostasIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/agenda': typeof AppAgendaRouteWithChildren
  '/app/aprovacoes': typeof AppAprovacoesRoute
  '/app/atividades': typeof AppAtividadesRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/cobertura': typeof AppCoberturaRoute
  '/app/competitiva': typeof AppCompetitivaRoute
  '/app/concorrentes': typeof AppConcorrentesRoute
  '/app/configuracoes': typeof AppConfiguracoesRouteWithChildren
  '/app/dashboard-geral': typeof AppDashboardGeralRoute
  '/app/documentos': typeof AppDocumentosRoute
  '/app/equipamentos': typeof AppEquipamentosRoute
  '/app/gestao': typeof AppGestaoRouteWithChildren
  '/app/perfil': typeof AppPerfilRoute
  '/app/produtividade': typeof AppProdutividadeRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/tarefas': typeof AppTarefasRoute
  '/app/': typeof AppIndexRoute
  '/api/nomus/test': typeof ApiNomusTestRoute
  '/app/admin/usuarios': typeof AppAdminUsuariosRoute
  '/app/agenda/$id': typeof AppAgendaIdRoute
  '/app/coldpro/$id': typeof AppColdproIdRoute
  '/app/coldpro/catalogo': typeof AppColdproCatalogoRoute
  '/app/coldpro/produtos': typeof AppColdproProdutosRoute
  '/app/configuracoes/api-nomus': typeof AppConfiguracoesApiNomusRoute
  '/app/configuracoes/nomus': typeof AppConfiguracoesNomusRouteWithChildren
  '/app/configuracoes/permissoes': typeof AppConfiguracoesPermissoesRoute
  '/app/crm/$id': typeof AppCrmIdRoute
  '/app/crm/closers-performance': typeof AppCrmClosersPerformanceRoute
  '/app/gestao/alertas-sdr': typeof AppGestaoAlertasSdrRoute
  '/app/gestao/atividades': typeof AppGestaoAtividadesRoute
  '/app/gestao/auditoria-sdr': typeof AppGestaoAuditoriaSdrRoute
  '/app/propostas/$id': typeof AppPropostasIdRouteWithChildren
  '/app/propostas/nova': typeof AppPropostasNovaRoute
  '/app/propostas/pedidos-nf': typeof AppPropostasPedidosNfRoute
  '/app/propostas/tabelas-preco': typeof AppPropostasTabelasPrecoRoute
  '/app/sdr/bank': typeof AppSdrBankRoute
  '/app/sdr/hot-deals': typeof AppSdrHotDealsRoute
  '/app/sdr/relatorios': typeof AppSdrRelatoriosRoute
  '/app/sdr/scripts': typeof AppSdrScriptsRoute
  '/app/sdr/sdr-performance': typeof AppSdrSdrPerformanceRoute
  '/app/sdr/wallet': typeof AppSdrWalletRoute
  '/app/sdr/war-room': typeof AppSdrWarRoomRoute
  '/app/vendas/carteira': typeof AppVendasCarteiraRoute
  '/app/coldpro/': typeof AppColdproIndexRoute
  '/app/configuracoes/': typeof AppConfiguracoesIndexRoute
  '/app/crm/': typeof AppCrmIndexRoute
  '/app/propostas/': typeof AppPropostasIndexRoute
  '/app/sdr/': typeof AppSdrIndexRoute
  '/_authenticated/app/sdr/novo-lead': typeof AuthenticatedAppSdrNovoLeadRoute
  '/api/public/hooks/nomus-cron': typeof ApiPublicHooksNomusCronRoute
  '/api/public/leads/site': typeof ApiPublicLeadsSiteRoute
  '/api/public/nomus/exhaustive-probe': typeof ApiPublicNomusExhaustiveProbeRoute
  '/api/public/nomus/produto-probe': typeof ApiPublicNomusProdutoProbeRoute
  '/api/public/nomus/tabela-preco-deep-probe': typeof ApiPublicNomusTabelaPrecoDeepProbeRoute
  '/api/public/nomus/tabela-preco-probe': typeof ApiPublicNomusTabelaPrecoProbeRoute
  '/app/configuracoes/nomus/importar-custos': typeof AppConfiguracoesNomusImportarCustosRoute
  '/app/configuracoes/templates/$id': typeof AppConfiguracoesTemplatesIdRoute
  '/app/gestao/carteiras/$userId': typeof AppGestaoCarteirasUserIdRoute
  '/app/propostas/$id/editor': typeof AppPropostasIdEditorRoute
  '/app/sdr/leads/$id': typeof AppSdrLeadsIdRoute
  '/app/configuracoes/templates/': typeof AppConfiguracoesTemplatesIndexRoute
  '/app/gestao/carteiras/': typeof AppGestaoCarteirasIndexRoute
  '/app/propostas/$id/': typeof AppPropostasIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/agenda'
    | '/app/aprovacoes'
    | '/app/atividades'
    | '/app/clientes'
    | '/app/cobertura'
    | '/app/competitiva'
    | '/app/concorrentes'
    | '/app/configuracoes'
    | '/app/dashboard-geral'
    | '/app/documentos'
    | '/app/equipamentos'
    | '/app/gestao'
    | '/app/perfil'
    | '/app/produtividade'
    | '/app/relatorios'
    | '/app/tarefas'
    | '/app/'
    | '/api/nomus/test'
    | '/app/admin/usuarios'
    | '/app/agenda/$id'
    | '/app/coldpro/$id'
    | '/app/coldpro/catalogo'
    | '/app/coldpro/produtos'
    | '/app/configuracoes/api-nomus'
    | '/app/configuracoes/nomus'
    | '/app/configuracoes/permissoes'
    | '/app/crm/$id'
    | '/app/crm/closers-performance'
    | '/app/gestao/alertas-sdr'
    | '/app/gestao/atividades'
    | '/app/gestao/auditoria-sdr'
    | '/app/propostas/$id'
    | '/app/propostas/nova'
    | '/app/propostas/pedidos-nf'
    | '/app/propostas/tabelas-preco'
    | '/app/sdr/bank'
    | '/app/sdr/hot-deals'
    | '/app/sdr/relatorios'
    | '/app/sdr/scripts'
    | '/app/sdr/sdr-performance'
    | '/app/sdr/wallet'
    | '/app/sdr/war-room'
    | '/app/vendas/carteira'
    | '/app/coldpro/'
    | '/app/configuracoes/'
    | '/app/crm/'
    | '/app/propostas/'
    | '/app/sdr/'
    | '/app/sdr/novo-lead'
    | '/api/public/hooks/nomus-cron'
    | '/api/public/leads/site'
    | '/api/public/nomus/exhaustive-probe'
    | '/api/public/nomus/produto-probe'
    | '/api/public/nomus/tabela-preco-deep-probe'
    | '/api/public/nomus/tabela-preco-probe'
    | '/app/configuracoes/nomus/importar-custos'
    | '/app/configuracoes/templates/$id'
    | '/app/gestao/carteiras/$userId'
    | '/app/propostas/$id/editor'
    | '/app/sdr/leads/$id'
    | '/app/configuracoes/templates/'
    | '/app/gestao/carteiras/'
    | '/app/propostas/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/agenda'
    | '/app/aprovacoes'
    | '/app/atividades'
    | '/app/clientes'
    | '/app/cobertura'
    | '/app/competitiva'
    | '/app/concorrentes'
    | '/app/dashboard-geral'
    | '/app/documentos'
    | '/app/equipamentos'
    | '/app/gestao'
    | '/app/perfil'
    | '/app/produtividade'
    | '/app/relatorios'
    | '/app/tarefas'
    | '/app'
    | '/api/nomus/test'
    | '/app/admin/usuarios'
    | '/app/agenda/$id'
    | '/app/coldpro/$id'
    | '/app/coldpro/catalogo'
    | '/app/coldpro/produtos'
    | '/app/configuracoes/api-nomus'
    | '/app/configuracoes/nomus'
    | '/app/configuracoes/permissoes'
    | '/app/crm/$id'
    | '/app/crm/closers-performance'
    | '/app/gestao/alertas-sdr'
    | '/app/gestao/atividades'
    | '/app/gestao/auditoria-sdr'
    | '/app/propostas/nova'
    | '/app/propostas/pedidos-nf'
    | '/app/propostas/tabelas-preco'
    | '/app/sdr/bank'
    | '/app/sdr/hot-deals'
    | '/app/sdr/relatorios'
    | '/app/sdr/scripts'
    | '/app/sdr/sdr-performance'
    | '/app/sdr/wallet'
    | '/app/sdr/war-room'
    | '/app/vendas/carteira'
    | '/app/coldpro'
    | '/app/configuracoes'
    | '/app/crm'
    | '/app/propostas'
    | '/app/sdr'
    | '/app/sdr/novo-lead'
    | '/api/public/hooks/nomus-cron'
    | '/api/public/leads/site'
    | '/api/public/nomus/exhaustive-probe'
    | '/api/public/nomus/produto-probe'
    | '/api/public/nomus/tabela-preco-deep-probe'
    | '/api/public/nomus/tabela-preco-probe'
    | '/app/configuracoes/nomus/importar-custos'
    | '/app/configuracoes/templates/$id'
    | '/app/gestao/carteiras/$userId'
    | '/app/propostas/$id/editor'
    | '/app/sdr/leads/$id'
    | '/app/configuracoes/templates'
    | '/app/gestao/carteiras'
    | '/app/propostas/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/app'
    | '/login'
    | '/app/agenda'
    | '/app/aprovacoes'
    | '/app/atividades'
    | '/app/clientes'
    | '/app/cobertura'
    | '/app/competitiva'
    | '/app/concorrentes'
    | '/app/configuracoes'
    | '/app/dashboard-geral'
    | '/app/documentos'
    | '/app/equipamentos'
    | '/app/gestao'
    | '/app/perfil'
    | '/app/produtividade'
    | '/app/relatorios'
    | '/app/tarefas'
    | '/app/'
    | '/api/nomus/test'
    | '/app/admin/usuarios'
    | '/app/agenda/$id'
    | '/app/coldpro/$id'
    | '/app/coldpro/catalogo'
    | '/app/coldpro/produtos'
    | '/app/configuracoes/api-nomus'
    | '/app/configuracoes/nomus'
    | '/app/configuracoes/permissoes'
    | '/app/crm/$id'
    | '/app/crm/closers-performance'
    | '/app/gestao/alertas-sdr'
    | '/app/gestao/atividades'
    | '/app/gestao/auditoria-sdr'
    | '/app/propostas/$id'
    | '/app/propostas/nova'
    | '/app/propostas/pedidos-nf'
    | '/app/propostas/tabelas-preco'
    | '/app/sdr/bank'
    | '/app/sdr/hot-deals'
    | '/app/sdr/relatorios'
    | '/app/sdr/scripts'
    | '/app/sdr/sdr-performance'
    | '/app/sdr/wallet'
    | '/app/sdr/war-room'
    | '/app/vendas/carteira'
    | '/app/coldpro/'
    | '/app/configuracoes/'
    | '/app/crm/'
    | '/app/propostas/'
    | '/app/sdr/'
    | '/_authenticated/app/sdr/novo-lead'
    | '/api/public/hooks/nomus-cron'
    | '/api/public/leads/site'
    | '/api/public/nomus/exhaustive-probe'
    | '/api/public/nomus/produto-probe'
    | '/api/public/nomus/tabela-preco-deep-probe'
    | '/api/public/nomus/tabela-preco-probe'
    | '/app/configuracoes/nomus/importar-custos'
    | '/app/configuracoes/templates/$id'
    | '/app/gestao/carteiras/$userId'
    | '/app/propostas/$id/editor'
    | '/app/sdr/leads/$id'
    | '/app/configuracoes/templates/'
    | '/app/gestao/carteiras/'
    | '/app/propostas/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiNomusTestRoute: typeof ApiNomusTestRoute
  ApiPublicHooksNomusCronRoute: typeof ApiPublicHooksNomusCronRoute
  ApiPublicLeadsSiteRoute: typeof ApiPublicLeadsSiteRoute
  ApiPublicNomusExhaustiveProbeRoute: typeof ApiPublicNomusExhaustiveProbeRoute
  ApiPublicNomusProdutoProbeRoute: typeof ApiPublicNomusProdutoProbeRoute
  ApiPublicNomusTabelaPrecoDeepProbeRoute: typeof ApiPublicNomusTabelaPrecoDeepProbeRoute
  ApiPublicNomusTabelaPrecoProbeRoute: typeof ApiPublicNomusTabelaPrecoProbeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tarefas': {
      id: '/app/tarefas'
      path: '/tarefas'
      fullPath: '/app/tarefas'
      preLoaderRoute: typeof AppTarefasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/produtividade': {
      id: '/app/produtividade'
      path: '/produtividade'
      fullPath: '/app/produtividade'
      preLoaderRoute: typeof AppProdutividadeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gestao': {
      id: '/app/gestao'
      path: '/gestao'
      fullPath: '/app/gestao'
      preLoaderRoute: typeof AppGestaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/equipamentos': {
      id: '/app/equipamentos'
      path: '/equipamentos'
      fullPath: '/app/equipamentos'
      preLoaderRoute: typeof AppEquipamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documentos': {
      id: '/app/documentos'
      path: '/documentos'
      fullPath: '/app/documentos'
      preLoaderRoute: typeof AppDocumentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard-geral': {
      id: '/app/dashboard-geral'
      path: '/dashboard-geral'
      fullPath: '/app/dashboard-geral'
      preLoaderRoute: typeof AppDashboardGeralRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/concorrentes': {
      id: '/app/concorrentes'
      path: '/concorrentes'
      fullPath: '/app/concorrentes'
      preLoaderRoute: typeof AppConcorrentesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/competitiva': {
      id: '/app/competitiva'
      path: '/competitiva'
      fullPath: '/app/competitiva'
      preLoaderRoute: typeof AppCompetitivaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cobertura': {
      id: '/app/cobertura'
      path: '/cobertura'
      fullPath: '/app/cobertura'
      preLoaderRoute: typeof AppCoberturaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/atividades': {
      id: '/app/atividades'
      path: '/atividades'
      fullPath: '/app/atividades'
      preLoaderRoute: typeof AppAtividadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/aprovacoes': {
      id: '/app/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/app/aprovacoes'
      preLoaderRoute: typeof AppAprovacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agenda': {
      id: '/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sdr/': {
      id: '/app/sdr/'
      path: '/sdr'
      fullPath: '/app/sdr/'
      preLoaderRoute: typeof AppSdrIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/propostas/': {
      id: '/app/propostas/'
      path: '/propostas'
      fullPath: '/app/propostas/'
      preLoaderRoute: typeof AppPropostasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm/': {
      id: '/app/crm/'
      path: '/crm'
      fullPath: '/app/crm/'
      preLoaderRoute: typeof AppCrmIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/': {
      id: '/app/configuracoes/'
      path: '/'
      fullPath: '/app/configuracoes/'
      preLoaderRoute: typeof AppConfiguracoesIndexRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/coldpro/': {
      id: '/app/coldpro/'
      path: '/coldpro'
      fullPath: '/app/coldpro/'
      preLoaderRoute: typeof AppColdproIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vendas/carteira': {
      id: '/app/vendas/carteira'
      path: '/vendas/carteira'
      fullPath: '/app/vendas/carteira'
      preLoaderRoute: typeof AppVendasCarteiraRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sdr/war-room': {
      id: '/app/sdr/war-room'
      path: '/sdr/war-room'
      fullPath: '/app/sdr/war-room'
      preLoaderRoute: typeof AppSdrWarRoomRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sdr/wallet': {
      id: '/app/sdr/wallet'
      path: '/sdr/wallet'
      fullPath: '/app/sdr/wallet'
      preLoaderRoute: typeof AppSdrWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sdr/sdr-performance': {
      id: '/app/sdr/sdr-performance'
      path: '/sdr/sdr-performance'
      fullPath: '/app/sdr/sdr-performance'
      preLoaderRoute: typeof AppSdrSdrPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sdr/scripts': {
      id: '/app/sdr/scripts'
      path: '/sdr/scripts'
      fullPath: '/app/sdr/scripts'
      preLoaderRoute: typeof AppSdrScriptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sdr/relatorios': {
      id: '/app/sdr/relatorios'
      path: '/sdr/relatorios'
      fullPath: '/app/sdr/relatorios'
      preLoaderRoute: typeof AppSdrRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sdr/hot-deals': {
      id: '/app/sdr/hot-deals'
      path: '/sdr/hot-deals'
      fullPath: '/app/sdr/hot-deals'
      preLoaderRoute: typeof AppSdrHotDealsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sdr/bank': {
      id: '/app/sdr/bank'
      path: '/sdr/bank'
      fullPath: '/app/sdr/bank'
      preLoaderRoute: typeof AppSdrBankRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/propostas/tabelas-preco': {
      id: '/app/propostas/tabelas-preco'
      path: '/propostas/tabelas-preco'
      fullPath: '/app/propostas/tabelas-preco'
      preLoaderRoute: typeof AppPropostasTabelasPrecoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/propostas/pedidos-nf': {
      id: '/app/propostas/pedidos-nf'
      path: '/propostas/pedidos-nf'
      fullPath: '/app/propostas/pedidos-nf'
      preLoaderRoute: typeof AppPropostasPedidosNfRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/propostas/nova': {
      id: '/app/propostas/nova'
      path: '/propostas/nova'
      fullPath: '/app/propostas/nova'
      preLoaderRoute: typeof AppPropostasNovaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/propostas/$id': {
      id: '/app/propostas/$id'
      path: '/propostas/$id'
      fullPath: '/app/propostas/$id'
      preLoaderRoute: typeof AppPropostasIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gestao/auditoria-sdr': {
      id: '/app/gestao/auditoria-sdr'
      path: '/auditoria-sdr'
      fullPath: '/app/gestao/auditoria-sdr'
      preLoaderRoute: typeof AppGestaoAuditoriaSdrRouteImport
      parentRoute: typeof AppGestaoRoute
    }
    '/app/gestao/atividades': {
      id: '/app/gestao/atividades'
      path: '/atividades'
      fullPath: '/app/gestao/atividades'
      preLoaderRoute: typeof AppGestaoAtividadesRouteImport
      parentRoute: typeof AppGestaoRoute
    }
    '/app/gestao/alertas-sdr': {
      id: '/app/gestao/alertas-sdr'
      path: '/alertas-sdr'
      fullPath: '/app/gestao/alertas-sdr'
      preLoaderRoute: typeof AppGestaoAlertasSdrRouteImport
      parentRoute: typeof AppGestaoRoute
    }
    '/app/crm/closers-performance': {
      id: '/app/crm/closers-performance'
      path: '/crm/closers-performance'
      fullPath: '/app/crm/closers-performance'
      preLoaderRoute: typeof AppCrmClosersPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm/$id': {
      id: '/app/crm/$id'
      path: '/crm/$id'
      fullPath: '/app/crm/$id'
      preLoaderRoute: typeof AppCrmIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/permissoes': {
      id: '/app/configuracoes/permissoes'
      path: '/permissoes'
      fullPath: '/app/configuracoes/permissoes'
      preLoaderRoute: typeof AppConfiguracoesPermissoesRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/configuracoes/nomus': {
      id: '/app/configuracoes/nomus'
      path: '/nomus'
      fullPath: '/app/configuracoes/nomus'
      preLoaderRoute: typeof AppConfiguracoesNomusRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/configuracoes/api-nomus': {
      id: '/app/configuracoes/api-nomus'
      path: '/api-nomus'
      fullPath: '/app/configuracoes/api-nomus'
      preLoaderRoute: typeof AppConfiguracoesApiNomusRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/coldpro/produtos': {
      id: '/app/coldpro/produtos'
      path: '/coldpro/produtos'
      fullPath: '/app/coldpro/produtos'
      preLoaderRoute: typeof AppColdproProdutosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coldpro/catalogo': {
      id: '/app/coldpro/catalogo'
      path: '/coldpro/catalogo'
      fullPath: '/app/coldpro/catalogo'
      preLoaderRoute: typeof AppColdproCatalogoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coldpro/$id': {
      id: '/app/coldpro/$id'
      path: '/coldpro/$id'
      fullPath: '/app/coldpro/$id'
      preLoaderRoute: typeof AppColdproIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agenda/$id': {
      id: '/app/agenda/$id'
      path: '/$id'
      fullPath: '/app/agenda/$id'
      preLoaderRoute: typeof AppAgendaIdRouteImport
      parentRoute: typeof AppAgendaRoute
    }
    '/app/admin/usuarios': {
      id: '/app/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/app/admin/usuarios'
      preLoaderRoute: typeof AppAdminUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/nomus/test': {
      id: '/api/nomus/test'
      path: '/api/nomus/test'
      fullPath: '/api/nomus/test'
      preLoaderRoute: typeof ApiNomusTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/propostas/$id/': {
      id: '/app/propostas/$id/'
      path: '/'
      fullPath: '/app/propostas/$id/'
      preLoaderRoute: typeof AppPropostasIdIndexRouteImport
      parentRoute: typeof AppPropostasIdRoute
    }
    '/app/gestao/carteiras/': {
      id: '/app/gestao/carteiras/'
      path: '/carteiras'
      fullPath: '/app/gestao/carteiras/'
      preLoaderRoute: typeof AppGestaoCarteirasIndexRouteImport
      parentRoute: typeof AppGestaoRoute
    }
    '/app/configuracoes/templates/': {
      id: '/app/configuracoes/templates/'
      path: '/templates'
      fullPath: '/app/configuracoes/templates/'
      preLoaderRoute: typeof AppConfiguracoesTemplatesIndexRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/sdr/leads/$id': {
      id: '/app/sdr/leads/$id'
      path: '/sdr/leads/$id'
      fullPath: '/app/sdr/leads/$id'
      preLoaderRoute: typeof AppSdrLeadsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/propostas/$id/editor': {
      id: '/app/propostas/$id/editor'
      path: '/editor'
      fullPath: '/app/propostas/$id/editor'
      preLoaderRoute: typeof AppPropostasIdEditorRouteImport
      parentRoute: typeof AppPropostasIdRoute
    }
    '/app/gestao/carteiras/$userId': {
      id: '/app/gestao/carteiras/$userId'
      path: '/carteiras/$userId'
      fullPath: '/app/gestao/carteiras/$userId'
      preLoaderRoute: typeof AppGestaoCarteirasUserIdRouteImport
      parentRoute: typeof AppGestaoRoute
    }
    '/app/configuracoes/templates/$id': {
      id: '/app/configuracoes/templates/$id'
      path: '/templates/$id'
      fullPath: '/app/configuracoes/templates/$id'
      preLoaderRoute: typeof AppConfiguracoesTemplatesIdRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/configuracoes/nomus/importar-custos': {
      id: '/app/configuracoes/nomus/importar-custos'
      path: '/importar-custos'
      fullPath: '/app/configuracoes/nomus/importar-custos'
      preLoaderRoute: typeof AppConfiguracoesNomusImportarCustosRouteImport
      parentRoute: typeof AppConfiguracoesNomusRoute
    }
    '/api/public/nomus/tabela-preco-probe': {
      id: '/api/public/nomus/tabela-preco-probe'
      path: '/api/public/nomus/tabela-preco-probe'
      fullPath: '/api/public/nomus/tabela-preco-probe'
      preLoaderRoute: typeof ApiPublicNomusTabelaPrecoProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nomus/tabela-preco-deep-probe': {
      id: '/api/public/nomus/tabela-preco-deep-probe'
      path: '/api/public/nomus/tabela-preco-deep-probe'
      fullPath: '/api/public/nomus/tabela-preco-deep-probe'
      preLoaderRoute: typeof ApiPublicNomusTabelaPrecoDeepProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nomus/produto-probe': {
      id: '/api/public/nomus/produto-probe'
      path: '/api/public/nomus/produto-probe'
      fullPath: '/api/public/nomus/produto-probe'
      preLoaderRoute: typeof ApiPublicNomusProdutoProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nomus/exhaustive-probe': {
      id: '/api/public/nomus/exhaustive-probe'
      path: '/api/public/nomus/exhaustive-probe'
      fullPath: '/api/public/nomus/exhaustive-probe'
      preLoaderRoute: typeof ApiPublicNomusExhaustiveProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads/site': {
      id: '/api/public/leads/site'
      path: '/api/public/leads/site'
      fullPath: '/api/public/leads/site'
      preLoaderRoute: typeof ApiPublicLeadsSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/nomus-cron': {
      id: '/api/public/hooks/nomus-cron'
      path: '/api/public/hooks/nomus-cron'
      fullPath: '/api/public/hooks/nomus-cron'
      preLoaderRoute: typeof ApiPublicHooksNomusCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/sdr/novo-lead': {
      id: '/_authenticated/app/sdr/novo-lead'
      path: '/app/sdr/novo-lead'
      fullPath: '/app/sdr/novo-lead'
      preLoaderRoute: typeof AuthenticatedAppSdrNovoLeadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppSdrNovoLeadRoute: typeof AuthenticatedAppSdrNovoLeadRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppSdrNovoLeadRoute: AuthenticatedAppSdrNovoLeadRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AppAgendaRouteChildren {
  AppAgendaIdRoute: typeof AppAgendaIdRoute
}

const AppAgendaRouteChildren: AppAgendaRouteChildren = {
  AppAgendaIdRoute: AppAgendaIdRoute,
}

const AppAgendaRouteWithChildren = AppAgendaRoute._addFileChildren(
  AppAgendaRouteChildren,
)

interface AppConfiguracoesNomusRouteChildren {
  AppConfiguracoesNomusImportarCustosRoute: typeof AppConfiguracoesNomusImportarCustosRoute
}

const AppConfiguracoesNomusRouteChildren: AppConfiguracoesNomusRouteChildren = {
  AppConfiguracoesNomusImportarCustosRoute:
    AppConfiguracoesNomusImportarCustosRoute,
}

const AppConfiguracoesNomusRouteWithChildren =
  AppConfiguracoesNomusRoute._addFileChildren(
    AppConfiguracoesNomusRouteChildren,
  )

interface AppConfiguracoesRouteChildren {
  AppConfiguracoesApiNomusRoute: typeof AppConfiguracoesApiNomusRoute
  AppConfiguracoesNomusRoute: typeof AppConfiguracoesNomusRouteWithChildren
  AppConfiguracoesPermissoesRoute: typeof AppConfiguracoesPermissoesRoute
  AppConfiguracoesIndexRoute: typeof AppConfiguracoesIndexRoute
  AppConfiguracoesTemplatesIdRoute: typeof AppConfiguracoesTemplatesIdRoute
  AppConfiguracoesTemplatesIndexRoute: typeof AppConfiguracoesTemplatesIndexRoute
}

const AppConfiguracoesRouteChildren: AppConfiguracoesRouteChildren = {
  AppConfiguracoesApiNomusRoute: AppConfiguracoesApiNomusRoute,
  AppConfiguracoesNomusRoute: AppConfiguracoesNomusRouteWithChildren,
  AppConfiguracoesPermissoesRoute: AppConfiguracoesPermissoesRoute,
  AppConfiguracoesIndexRoute: AppConfiguracoesIndexRoute,
  AppConfiguracoesTemplatesIdRoute: AppConfiguracoesTemplatesIdRoute,
  AppConfiguracoesTemplatesIndexRoute: AppConfiguracoesTemplatesIndexRoute,
}

const AppConfiguracoesRouteWithChildren =
  AppConfiguracoesRoute._addFileChildren(AppConfiguracoesRouteChildren)

interface AppGestaoRouteChildren {
  AppGestaoAlertasSdrRoute: typeof AppGestaoAlertasSdrRoute
  AppGestaoAtividadesRoute: typeof AppGestaoAtividadesRoute
  AppGestaoAuditoriaSdrRoute: typeof AppGestaoAuditoriaSdrRoute
  AppGestaoCarteirasUserIdRoute: typeof AppGestaoCarteirasUserIdRoute
  AppGestaoCarteirasIndexRoute: typeof AppGestaoCarteirasIndexRoute
}

const AppGestaoRouteChildren: AppGestaoRouteChildren = {
  AppGestaoAlertasSdrRoute: AppGestaoAlertasSdrRoute,
  AppGestaoAtividadesRoute: AppGestaoAtividadesRoute,
  AppGestaoAuditoriaSdrRoute: AppGestaoAuditoriaSdrRoute,
  AppGestaoCarteirasUserIdRoute: AppGestaoCarteirasUserIdRoute,
  AppGestaoCarteirasIndexRoute: AppGestaoCarteirasIndexRoute,
}

const AppGestaoRouteWithChildren = AppGestaoRoute._addFileChildren(
  AppGestaoRouteChildren,
)

interface AppPropostasIdRouteChildren {
  AppPropostasIdEditorRoute: typeof AppPropostasIdEditorRoute
  AppPropostasIdIndexRoute: typeof AppPropostasIdIndexRoute
}

const AppPropostasIdRouteChildren: AppPropostasIdRouteChildren = {
  AppPropostasIdEditorRoute: AppPropostasIdEditorRoute,
  AppPropostasIdIndexRoute: AppPropostasIdIndexRoute,
}

const AppPropostasIdRouteWithChildren = AppPropostasIdRoute._addFileChildren(
  AppPropostasIdRouteChildren,
)

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRouteWithChildren
  AppAprovacoesRoute: typeof AppAprovacoesRoute
  AppAtividadesRoute: typeof AppAtividadesRoute
  AppClientesRoute: typeof AppClientesRoute
  AppCoberturaRoute: typeof AppCoberturaRoute
  AppCompetitivaRoute: typeof AppCompetitivaRoute
  AppConcorrentesRoute: typeof AppConcorrentesRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRouteWithChildren
  AppDashboardGeralRoute: typeof AppDashboardGeralRoute
  AppDocumentosRoute: typeof AppDocumentosRoute
  AppEquipamentosRoute: typeof AppEquipamentosRoute
  AppGestaoRoute: typeof AppGestaoRouteWithChildren
  AppPerfilRoute: typeof AppPerfilRoute
  AppProdutividadeRoute: typeof AppProdutividadeRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppTarefasRoute: typeof AppTarefasRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminUsuariosRoute: typeof AppAdminUsuariosRoute
  AppColdproIdRoute: typeof AppColdproIdRoute
  AppColdproCatalogoRoute: typeof AppColdproCatalogoRoute
  AppColdproProdutosRoute: typeof AppColdproProdutosRoute
  AppCrmIdRoute: typeof AppCrmIdRoute
  AppCrmClosersPerformanceRoute: typeof AppCrmClosersPerformanceRoute
  AppPropostasIdRoute: typeof AppPropostasIdRouteWithChildren
  AppPropostasNovaRoute: typeof AppPropostasNovaRoute
  AppPropostasPedidosNfRoute: typeof AppPropostasPedidosNfRoute
  AppPropostasTabelasPrecoRoute: typeof AppPropostasTabelasPrecoRoute
  AppSdrBankRoute: typeof AppSdrBankRoute
  AppSdrHotDealsRoute: typeof AppSdrHotDealsRoute
  AppSdrRelatoriosRoute: typeof AppSdrRelatoriosRoute
  AppSdrScriptsRoute: typeof AppSdrScriptsRoute
  AppSdrSdrPerformanceRoute: typeof AppSdrSdrPerformanceRoute
  AppSdrWalletRoute: typeof AppSdrWalletRoute
  AppSdrWarRoomRoute: typeof AppSdrWarRoomRoute
  AppVendasCarteiraRoute: typeof AppVendasCarteiraRoute
  AppColdproIndexRoute: typeof AppColdproIndexRoute
  AppCrmIndexRoute: typeof AppCrmIndexRoute
  AppPropostasIndexRoute: typeof AppPropostasIndexRoute
  AppSdrIndexRoute: typeof AppSdrIndexRoute
  AppSdrLeadsIdRoute: typeof AppSdrLeadsIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRouteWithChildren,
  AppAprovacoesRoute: AppAprovacoesRoute,
  AppAtividadesRoute: AppAtividadesRoute,
  AppClientesRoute: AppClientesRoute,
  AppCoberturaRoute: AppCoberturaRoute,
  AppCompetitivaRoute: AppCompetitivaRoute,
  AppConcorrentesRoute: AppConcorrentesRoute,
  AppConfiguracoesRoute: AppConfiguracoesRouteWithChildren,
  AppDashboardGeralRoute: AppDashboardGeralRoute,
  AppDocumentosRoute: AppDocumentosRoute,
  AppEquipamentosRoute: AppEquipamentosRoute,
  AppGestaoRoute: AppGestaoRouteWithChildren,
  AppPerfilRoute: AppPerfilRoute,
  AppProdutividadeRoute: AppProdutividadeRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppTarefasRoute: AppTarefasRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminUsuariosRoute: AppAdminUsuariosRoute,
  AppColdproIdRoute: AppColdproIdRoute,
  AppColdproCatalogoRoute: AppColdproCatalogoRoute,
  AppColdproProdutosRoute: AppColdproProdutosRoute,
  AppCrmIdRoute: AppCrmIdRoute,
  AppCrmClosersPerformanceRoute: AppCrmClosersPerformanceRoute,
  AppPropostasIdRoute: AppPropostasIdRouteWithChildren,
  AppPropostasNovaRoute: AppPropostasNovaRoute,
  AppPropostasPedidosNfRoute: AppPropostasPedidosNfRoute,
  AppPropostasTabelasPrecoRoute: AppPropostasTabelasPrecoRoute,
  AppSdrBankRoute: AppSdrBankRoute,
  AppSdrHotDealsRoute: AppSdrHotDealsRoute,
  AppSdrRelatoriosRoute: AppSdrRelatoriosRoute,
  AppSdrScriptsRoute: AppSdrScriptsRoute,
  AppSdrSdrPerformanceRoute: AppSdrSdrPerformanceRoute,
  AppSdrWalletRoute: AppSdrWalletRoute,
  AppSdrWarRoomRoute: AppSdrWarRoomRoute,
  AppVendasCarteiraRoute: AppVendasCarteiraRoute,
  AppColdproIndexRoute: AppColdproIndexRoute,
  AppCrmIndexRoute: AppCrmIndexRoute,
  AppPropostasIndexRoute: AppPropostasIndexRoute,
  AppSdrIndexRoute: AppSdrIndexRoute,
  AppSdrLeadsIdRoute: AppSdrLeadsIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiNomusTestRoute: ApiNomusTestRoute,
  ApiPublicHooksNomusCronRoute: ApiPublicHooksNomusCronRoute,
  ApiPublicLeadsSiteRoute: ApiPublicLeadsSiteRoute,
  ApiPublicNomusExhaustiveProbeRoute: ApiPublicNomusExhaustiveProbeRoute,
  ApiPublicNomusProdutoProbeRoute: ApiPublicNomusProdutoProbeRoute,
  ApiPublicNomusTabelaPrecoDeepProbeRoute:
    ApiPublicNomusTabelaPrecoDeepProbeRoute,
  ApiPublicNomusTabelaPrecoProbeRoute: ApiPublicNomusTabelaPrecoProbeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
