/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppPropostasIndexRouteImport } from './routes/app.propostas.index'
import { Route as AppPropostasNovaRouteImport } from './routes/app.propostas.nova'
import { Route as AppPropostasIdRouteImport } from './routes/app.propostas.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPropostasIndexRoute = AppPropostasIndexRouteImport.update({
  id: '/propostas/',
  path: '/propostas/',
  getParentRoute: () => AppRoute,
} as any)
const AppPropostasNovaRoute = AppPropostasNovaRouteImport.update({
  id: '/propostas/nova',
  path: '/propostas/nova',
  getParentRoute: () => AppRoute,
} as any)
const AppPropostasIdRoute = AppPropostasIdRouteImport.update({
  id: '/propostas/$id',
  path: '/propostas/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/': typeof AppIndexRoute
  '/app/propostas/$id': typeof AppPropostasIdRoute
  '/app/propostas/nova': typeof AppPropostasNovaRoute
  '/app/propostas/': typeof AppPropostasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app': typeof AppIndexRoute
  '/app/propostas/$id': typeof AppPropostasIdRoute
  '/app/propostas/nova': typeof AppPropostasNovaRoute
  '/app/propostas': typeof AppPropostasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/': typeof AppIndexRoute
  '/app/propostas/$id': typeof AppPropostasIdRoute
  '/app/propostas/nova': typeof AppPropostasNovaRoute
  '/app/propostas/': typeof AppPropostasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/'
    | '/app/propostas/$id'
    | '/app/propostas/nova'
    | '/app/propostas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app'
    | '/app/propostas/$id'
    | '/app/propostas/nova'
    | '/app/propostas'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/'
    | '/app/propostas/$id'
    | '/app/propostas/nova'
    | '/app/propostas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/propostas/': {
      id: '/app/propostas/'
      path: '/propostas'
      fullPath: '/app/propostas/'
      preLoaderRoute: typeof AppPropostasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/propostas/nova': {
      id: '/app/propostas/nova'
      path: '/propostas/nova'
      fullPath: '/app/propostas/nova'
      preLoaderRoute: typeof AppPropostasNovaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/propostas/$id': {
      id: '/app/propostas/$id'
      path: '/propostas/$id'
      fullPath: '/app/propostas/$id'
      preLoaderRoute: typeof AppPropostasIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppPropostasIdRoute: typeof AppPropostasIdRoute
  AppPropostasNovaRoute: typeof AppPropostasNovaRoute
  AppPropostasIndexRoute: typeof AppPropostasIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppPropostasIdRoute: AppPropostasIdRoute,
  AppPropostasNovaRoute: AppPropostasNovaRoute,
  AppPropostasIndexRoute: AppPropostasIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
