/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as HooksNomusCronRouteImport } from './routes/hooks/nomus-cron'
import { Route as AppTarefasRouteImport } from './routes/app.tarefas'
import { Route as AppSeletorRouteImport } from './routes/app.seletor'
import { Route as AppRelatoriosRouteImport } from './routes/app.relatorios'
import { Route as AppEquipamentosRouteImport } from './routes/app.equipamentos'
import { Route as AppDocumentosRouteImport } from './routes/app.documentos'
import { Route as AppCrmRouteImport } from './routes/app.crm'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppConcorrentesRouteImport } from './routes/app.concorrentes'
import { Route as AppCompetitivaRouteImport } from './routes/app.competitiva'
import { Route as AppClientesRouteImport } from './routes/app.clientes'
import { Route as AppAprovacoesRouteImport } from './routes/app.aprovacoes'
import { Route as AppPropostasIndexRouteImport } from './routes/app.propostas.index'
import { Route as AppConfiguracoesIndexRouteImport } from './routes/app.configuracoes.index'
import { Route as AppColdproIndexRouteImport } from './routes/app.coldpro.index'
import { Route as AppPropostasPedidosNfRouteImport } from './routes/app.propostas.pedidos-nf'
import { Route as AppPropostasNovaRouteImport } from './routes/app.propostas.nova'
import { Route as AppPropostasIdRouteImport } from './routes/app.propostas.$id'
import { Route as AppCrmIdRouteImport } from './routes/app.crm.$id'
import { Route as AppConfiguracoesNomusRouteImport } from './routes/app.configuracoes.nomus'
import { Route as AppConfiguracoesApiNomusRouteImport } from './routes/app.configuracoes.api-nomus'
import { Route as AppColdproCatalogoRouteImport } from './routes/app.coldpro.catalogo'
import { Route as AppColdproIdRouteImport } from './routes/app.coldpro.$id'
import { Route as ApiNomusTestRouteImport } from './routes/api.nomus.test'
import { Route as AppPropostasIdIndexRouteImport } from './routes/app.propostas.$id.index'
import { Route as AppConfiguracoesTemplatesIndexRouteImport } from './routes/app.configuracoes.templates.index'
import { Route as AppPropostasIdEditorRouteImport } from './routes/app.propostas.$id.editor'
import { Route as AppConfiguracoesTemplatesIdRouteImport } from './routes/app.configuracoes.templates.$id'
import { Route as AppConfiguracoesNomusImportarCustosRouteImport } from './routes/app.configuracoes.nomus.importar-custos'
import { Route as ApiPublicNomusTabelaPrecoProbeRouteImport } from './routes/api.public.nomus.tabela-preco-probe'
import { Route as ApiPublicNomusTabelaPrecoDeepProbeRouteImport } from './routes/api.public.nomus.tabela-preco-deep-probe'
import { Route as ApiPublicNomusProdutoProbeRouteImport } from './routes/api.public.nomus.produto-probe'
import { Route as ApiPublicNomusExhaustiveProbeRouteImport } from './routes/api.public.nomus.exhaustive-probe'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const HooksNomusCronRoute = HooksNomusCronRouteImport.update({
  id: '/hooks/nomus-cron',
  path: '/hooks/nomus-cron',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTarefasRoute = AppTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AppRoute,
} as any)
const AppSeletorRoute = AppSeletorRouteImport.update({
  id: '/seletor',
  path: '/seletor',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipamentosRoute = AppEquipamentosRouteImport.update({
  id: '/equipamentos',
  path: '/equipamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentosRoute = AppDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppConcorrentesRoute = AppConcorrentesRouteImport.update({
  id: '/concorrentes',
  path: '/concorrentes',
  getParentRoute: () => AppRoute,
} as any)
const AppCompetitivaRoute = AppCompetitivaRouteImport.update({
  id: '/competitiva',
  path: '/competitiva',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppAprovacoesRoute = AppAprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppPropostasIndexRoute = AppPropostasIndexRouteImport.update({
  id: '/propostas/',
  path: '/propostas/',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesIndexRoute = AppConfiguracoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppConfiguracoesRoute,
} as any)
const AppColdproIndexRoute = AppColdproIndexRouteImport.update({
  id: '/coldpro/',
  path: '/coldpro/',
  getParentRoute: () => AppRoute,
} as any)
const AppPropostasPedidosNfRoute = AppPropostasPedidosNfRouteImport.update({
  id: '/propostas/pedidos-nf',
  path: '/propostas/pedidos-nf',
  getParentRoute: () => AppRoute,
} as any)
const AppPropostasNovaRoute = AppPropostasNovaRouteImport.update({
  id: '/propostas/nova',
  path: '/propostas/nova',
  getParentRoute: () => AppRoute,
} as any)
const AppPropostasIdRoute = AppPropostasIdRouteImport.update({
  id: '/propostas/$id',
  path: '/propostas/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmIdRoute = AppCrmIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppConfiguracoesNomusRoute = AppConfiguracoesNomusRouteImport.update({
  id: '/nomus',
  path: '/nomus',
  getParentRoute: () => AppConfiguracoesRoute,
} as any)
const AppConfiguracoesApiNomusRoute =
  AppConfiguracoesApiNomusRouteImport.update({
    id: '/api-nomus',
    path: '/api-nomus',
    getParentRoute: () => AppConfiguracoesRoute,
  } as any)
const AppColdproCatalogoRoute = AppColdproCatalogoRouteImport.update({
  id: '/coldpro/catalogo',
  path: '/coldpro/catalogo',
  getParentRoute: () => AppRoute,
} as any)
const AppColdproIdRoute = AppColdproIdRouteImport.update({
  id: '/coldpro/$id',
  path: '/coldpro/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiNomusTestRoute = ApiNomusTestRouteImport.update({
  id: '/api/nomus/test',
  path: '/api/nomus/test',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPropostasIdIndexRoute = AppPropostasIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPropostasIdRoute,
} as any)
const AppConfiguracoesTemplatesIndexRoute =
  AppConfiguracoesTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AppConfiguracoesRoute,
  } as any)
const AppPropostasIdEditorRoute = AppPropostasIdEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AppPropostasIdRoute,
} as any)
const AppConfiguracoesTemplatesIdRoute =
  AppConfiguracoesTemplatesIdRouteImport.update({
    id: '/templates/$id',
    path: '/templates/$id',
    getParentRoute: () => AppConfiguracoesRoute,
  } as any)
const AppConfiguracoesNomusImportarCustosRoute =
  AppConfiguracoesNomusImportarCustosRouteImport.update({
    id: '/importar-custos',
    path: '/importar-custos',
    getParentRoute: () => AppConfiguracoesNomusRoute,
  } as any)
const ApiPublicNomusTabelaPrecoProbeRoute =
  ApiPublicNomusTabelaPrecoProbeRouteImport.update({
    id: '/api/public/nomus/tabela-preco-probe',
    path: '/api/public/nomus/tabela-preco-probe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNomusTabelaPrecoDeepProbeRoute =
  ApiPublicNomusTabelaPrecoDeepProbeRouteImport.update({
    id: '/api/public/nomus/tabela-preco-deep-probe',
    path: '/api/public/nomus/tabela-preco-deep-probe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNomusProdutoProbeRoute =
  ApiPublicNomusProdutoProbeRouteImport.update({
    id: '/api/public/nomus/produto-probe',
    path: '/api/public/nomus/produto-probe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNomusExhaustiveProbeRoute =
  ApiPublicNomusExhaustiveProbeRouteImport.update({
    id: '/api/public/nomus/exhaustive-probe',
    path: '/api/public/nomus/exhaustive-probe',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/aprovacoes': typeof AppAprovacoesRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/competitiva': typeof AppCompetitivaRoute
  '/app/concorrentes': typeof AppConcorrentesRoute
  '/app/configuracoes': typeof AppConfiguracoesRouteWithChildren
  '/app/crm': typeof AppCrmRouteWithChildren
  '/app/documentos': typeof AppDocumentosRoute
  '/app/equipamentos': typeof AppEquipamentosRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/seletor': typeof AppSeletorRoute
  '/app/tarefas': typeof AppTarefasRoute
  '/hooks/nomus-cron': typeof HooksNomusCronRoute
  '/app/': typeof AppIndexRoute
  '/api/nomus/test': typeof ApiNomusTestRoute
  '/app/coldpro/$id': typeof AppColdproIdRoute
  '/app/coldpro/catalogo': typeof AppColdproCatalogoRoute
  '/app/configuracoes/api-nomus': typeof AppConfiguracoesApiNomusRoute
  '/app/configuracoes/nomus': typeof AppConfiguracoesNomusRouteWithChildren
  '/app/crm/$id': typeof AppCrmIdRoute
  '/app/propostas/$id': typeof AppPropostasIdRouteWithChildren
  '/app/propostas/nova': typeof AppPropostasNovaRoute
  '/app/propostas/pedidos-nf': typeof AppPropostasPedidosNfRoute
  '/app/coldpro/': typeof AppColdproIndexRoute
  '/app/configuracoes/': typeof AppConfiguracoesIndexRoute
  '/app/propostas/': typeof AppPropostasIndexRoute
  '/api/public/nomus/exhaustive-probe': typeof ApiPublicNomusExhaustiveProbeRoute
  '/api/public/nomus/produto-probe': typeof ApiPublicNomusProdutoProbeRoute
  '/api/public/nomus/tabela-preco-deep-probe': typeof ApiPublicNomusTabelaPrecoDeepProbeRoute
  '/api/public/nomus/tabela-preco-probe': typeof ApiPublicNomusTabelaPrecoProbeRoute
  '/app/configuracoes/nomus/importar-custos': typeof AppConfiguracoesNomusImportarCustosRoute
  '/app/configuracoes/templates/$id': typeof AppConfiguracoesTemplatesIdRoute
  '/app/propostas/$id/editor': typeof AppPropostasIdEditorRoute
  '/app/configuracoes/templates/': typeof AppConfiguracoesTemplatesIndexRoute
  '/app/propostas/$id/': typeof AppPropostasIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/aprovacoes': typeof AppAprovacoesRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/competitiva': typeof AppCompetitivaRoute
  '/app/concorrentes': typeof AppConcorrentesRoute
  '/app/crm': typeof AppCrmRouteWithChildren
  '/app/documentos': typeof AppDocumentosRoute
  '/app/equipamentos': typeof AppEquipamentosRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/seletor': typeof AppSeletorRoute
  '/app/tarefas': typeof AppTarefasRoute
  '/hooks/nomus-cron': typeof HooksNomusCronRoute
  '/app': typeof AppIndexRoute
  '/api/nomus/test': typeof ApiNomusTestRoute
  '/app/coldpro/$id': typeof AppColdproIdRoute
  '/app/coldpro/catalogo': typeof AppColdproCatalogoRoute
  '/app/configuracoes/api-nomus': typeof AppConfiguracoesApiNomusRoute
  '/app/configuracoes/nomus': typeof AppConfiguracoesNomusRouteWithChildren
  '/app/crm/$id': typeof AppCrmIdRoute
  '/app/propostas/nova': typeof AppPropostasNovaRoute
  '/app/propostas/pedidos-nf': typeof AppPropostasPedidosNfRoute
  '/app/coldpro': typeof AppColdproIndexRoute
  '/app/configuracoes': typeof AppConfiguracoesIndexRoute
  '/app/propostas': typeof AppPropostasIndexRoute
  '/api/public/nomus/exhaustive-probe': typeof ApiPublicNomusExhaustiveProbeRoute
  '/api/public/nomus/produto-probe': typeof ApiPublicNomusProdutoProbeRoute
  '/api/public/nomus/tabela-preco-deep-probe': typeof ApiPublicNomusTabelaPrecoDeepProbeRoute
  '/api/public/nomus/tabela-preco-probe': typeof ApiPublicNomusTabelaPrecoProbeRoute
  '/app/configuracoes/nomus/importar-custos': typeof AppConfiguracoesNomusImportarCustosRoute
  '/app/configuracoes/templates/$id': typeof AppConfiguracoesTemplatesIdRoute
  '/app/propostas/$id/editor': typeof AppPropostasIdEditorRoute
  '/app/configuracoes/templates': typeof AppConfiguracoesTemplatesIndexRoute
  '/app/propostas/$id': typeof AppPropostasIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/aprovacoes': typeof AppAprovacoesRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/competitiva': typeof AppCompetitivaRoute
  '/app/concorrentes': typeof AppConcorrentesRoute
  '/app/configuracoes': typeof AppConfiguracoesRouteWithChildren
  '/app/crm': typeof AppCrmRouteWithChildren
  '/app/documentos': typeof AppDocumentosRoute
  '/app/equipamentos': typeof AppEquipamentosRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/seletor': typeof AppSeletorRoute
  '/app/tarefas': typeof AppTarefasRoute
  '/hooks/nomus-cron': typeof HooksNomusCronRoute
  '/app/': typeof AppIndexRoute
  '/api/nomus/test': typeof ApiNomusTestRoute
  '/app/coldpro/$id': typeof AppColdproIdRoute
  '/app/coldpro/catalogo': typeof AppColdproCatalogoRoute
  '/app/configuracoes/api-nomus': typeof AppConfiguracoesApiNomusRoute
  '/app/configuracoes/nomus': typeof AppConfiguracoesNomusRouteWithChildren
  '/app/crm/$id': typeof AppCrmIdRoute
  '/app/propostas/$id': typeof AppPropostasIdRouteWithChildren
  '/app/propostas/nova': typeof AppPropostasNovaRoute
  '/app/propostas/pedidos-nf': typeof AppPropostasPedidosNfRoute
  '/app/coldpro/': typeof AppColdproIndexRoute
  '/app/configuracoes/': typeof AppConfiguracoesIndexRoute
  '/app/propostas/': typeof AppPropostasIndexRoute
  '/api/public/nomus/exhaustive-probe': typeof ApiPublicNomusExhaustiveProbeRoute
  '/api/public/nomus/produto-probe': typeof ApiPublicNomusProdutoProbeRoute
  '/api/public/nomus/tabela-preco-deep-probe': typeof ApiPublicNomusTabelaPrecoDeepProbeRoute
  '/api/public/nomus/tabela-preco-probe': typeof ApiPublicNomusTabelaPrecoProbeRoute
  '/app/configuracoes/nomus/importar-custos': typeof AppConfiguracoesNomusImportarCustosRoute
  '/app/configuracoes/templates/$id': typeof AppConfiguracoesTemplatesIdRoute
  '/app/propostas/$id/editor': typeof AppPropostasIdEditorRoute
  '/app/configuracoes/templates/': typeof AppConfiguracoesTemplatesIndexRoute
  '/app/propostas/$id/': typeof AppPropostasIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/aprovacoes'
    | '/app/clientes'
    | '/app/competitiva'
    | '/app/concorrentes'
    | '/app/configuracoes'
    | '/app/crm'
    | '/app/documentos'
    | '/app/equipamentos'
    | '/app/relatorios'
    | '/app/seletor'
    | '/app/tarefas'
    | '/hooks/nomus-cron'
    | '/app/'
    | '/api/nomus/test'
    | '/app/coldpro/$id'
    | '/app/coldpro/catalogo'
    | '/app/configuracoes/api-nomus'
    | '/app/configuracoes/nomus'
    | '/app/crm/$id'
    | '/app/propostas/$id'
    | '/app/propostas/nova'
    | '/app/propostas/pedidos-nf'
    | '/app/coldpro/'
    | '/app/configuracoes/'
    | '/app/propostas/'
    | '/api/public/nomus/exhaustive-probe'
    | '/api/public/nomus/produto-probe'
    | '/api/public/nomus/tabela-preco-deep-probe'
    | '/api/public/nomus/tabela-preco-probe'
    | '/app/configuracoes/nomus/importar-custos'
    | '/app/configuracoes/templates/$id'
    | '/app/propostas/$id/editor'
    | '/app/configuracoes/templates/'
    | '/app/propostas/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/aprovacoes'
    | '/app/clientes'
    | '/app/competitiva'
    | '/app/concorrentes'
    | '/app/crm'
    | '/app/documentos'
    | '/app/equipamentos'
    | '/app/relatorios'
    | '/app/seletor'
    | '/app/tarefas'
    | '/hooks/nomus-cron'
    | '/app'
    | '/api/nomus/test'
    | '/app/coldpro/$id'
    | '/app/coldpro/catalogo'
    | '/app/configuracoes/api-nomus'
    | '/app/configuracoes/nomus'
    | '/app/crm/$id'
    | '/app/propostas/nova'
    | '/app/propostas/pedidos-nf'
    | '/app/coldpro'
    | '/app/configuracoes'
    | '/app/propostas'
    | '/api/public/nomus/exhaustive-probe'
    | '/api/public/nomus/produto-probe'
    | '/api/public/nomus/tabela-preco-deep-probe'
    | '/api/public/nomus/tabela-preco-probe'
    | '/app/configuracoes/nomus/importar-custos'
    | '/app/configuracoes/templates/$id'
    | '/app/propostas/$id/editor'
    | '/app/configuracoes/templates'
    | '/app/propostas/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/aprovacoes'
    | '/app/clientes'
    | '/app/competitiva'
    | '/app/concorrentes'
    | '/app/configuracoes'
    | '/app/crm'
    | '/app/documentos'
    | '/app/equipamentos'
    | '/app/relatorios'
    | '/app/seletor'
    | '/app/tarefas'
    | '/hooks/nomus-cron'
    | '/app/'
    | '/api/nomus/test'
    | '/app/coldpro/$id'
    | '/app/coldpro/catalogo'
    | '/app/configuracoes/api-nomus'
    | '/app/configuracoes/nomus'
    | '/app/crm/$id'
    | '/app/propostas/$id'
    | '/app/propostas/nova'
    | '/app/propostas/pedidos-nf'
    | '/app/coldpro/'
    | '/app/configuracoes/'
    | '/app/propostas/'
    | '/api/public/nomus/exhaustive-probe'
    | '/api/public/nomus/produto-probe'
    | '/api/public/nomus/tabela-preco-deep-probe'
    | '/api/public/nomus/tabela-preco-probe'
    | '/app/configuracoes/nomus/importar-custos'
    | '/app/configuracoes/templates/$id'
    | '/app/propostas/$id/editor'
    | '/app/configuracoes/templates/'
    | '/app/propostas/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  HooksNomusCronRoute: typeof HooksNomusCronRoute
  ApiNomusTestRoute: typeof ApiNomusTestRoute
  ApiPublicNomusExhaustiveProbeRoute: typeof ApiPublicNomusExhaustiveProbeRoute
  ApiPublicNomusProdutoProbeRoute: typeof ApiPublicNomusProdutoProbeRoute
  ApiPublicNomusTabelaPrecoDeepProbeRoute: typeof ApiPublicNomusTabelaPrecoDeepProbeRoute
  ApiPublicNomusTabelaPrecoProbeRoute: typeof ApiPublicNomusTabelaPrecoProbeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/hooks/nomus-cron': {
      id: '/hooks/nomus-cron'
      path: '/hooks/nomus-cron'
      fullPath: '/hooks/nomus-cron'
      preLoaderRoute: typeof HooksNomusCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tarefas': {
      id: '/app/tarefas'
      path: '/tarefas'
      fullPath: '/app/tarefas'
      preLoaderRoute: typeof AppTarefasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/seletor': {
      id: '/app/seletor'
      path: '/seletor'
      fullPath: '/app/seletor'
      preLoaderRoute: typeof AppSeletorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/equipamentos': {
      id: '/app/equipamentos'
      path: '/equipamentos'
      fullPath: '/app/equipamentos'
      preLoaderRoute: typeof AppEquipamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documentos': {
      id: '/app/documentos'
      path: '/documentos'
      fullPath: '/app/documentos'
      preLoaderRoute: typeof AppDocumentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm': {
      id: '/app/crm'
      path: '/crm'
      fullPath: '/app/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/concorrentes': {
      id: '/app/concorrentes'
      path: '/concorrentes'
      fullPath: '/app/concorrentes'
      preLoaderRoute: typeof AppConcorrentesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/competitiva': {
      id: '/app/competitiva'
      path: '/competitiva'
      fullPath: '/app/competitiva'
      preLoaderRoute: typeof AppCompetitivaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/aprovacoes': {
      id: '/app/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/app/aprovacoes'
      preLoaderRoute: typeof AppAprovacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/propostas/': {
      id: '/app/propostas/'
      path: '/propostas'
      fullPath: '/app/propostas/'
      preLoaderRoute: typeof AppPropostasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/': {
      id: '/app/configuracoes/'
      path: '/'
      fullPath: '/app/configuracoes/'
      preLoaderRoute: typeof AppConfiguracoesIndexRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/coldpro/': {
      id: '/app/coldpro/'
      path: '/coldpro'
      fullPath: '/app/coldpro/'
      preLoaderRoute: typeof AppColdproIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/propostas/pedidos-nf': {
      id: '/app/propostas/pedidos-nf'
      path: '/propostas/pedidos-nf'
      fullPath: '/app/propostas/pedidos-nf'
      preLoaderRoute: typeof AppPropostasPedidosNfRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/propostas/nova': {
      id: '/app/propostas/nova'
      path: '/propostas/nova'
      fullPath: '/app/propostas/nova'
      preLoaderRoute: typeof AppPropostasNovaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/propostas/$id': {
      id: '/app/propostas/$id'
      path: '/propostas/$id'
      fullPath: '/app/propostas/$id'
      preLoaderRoute: typeof AppPropostasIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm/$id': {
      id: '/app/crm/$id'
      path: '/$id'
      fullPath: '/app/crm/$id'
      preLoaderRoute: typeof AppCrmIdRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/app/configuracoes/nomus': {
      id: '/app/configuracoes/nomus'
      path: '/nomus'
      fullPath: '/app/configuracoes/nomus'
      preLoaderRoute: typeof AppConfiguracoesNomusRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/configuracoes/api-nomus': {
      id: '/app/configuracoes/api-nomus'
      path: '/api-nomus'
      fullPath: '/app/configuracoes/api-nomus'
      preLoaderRoute: typeof AppConfiguracoesApiNomusRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/coldpro/catalogo': {
      id: '/app/coldpro/catalogo'
      path: '/coldpro/catalogo'
      fullPath: '/app/coldpro/catalogo'
      preLoaderRoute: typeof AppColdproCatalogoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coldpro/$id': {
      id: '/app/coldpro/$id'
      path: '/coldpro/$id'
      fullPath: '/app/coldpro/$id'
      preLoaderRoute: typeof AppColdproIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/nomus/test': {
      id: '/api/nomus/test'
      path: '/api/nomus/test'
      fullPath: '/api/nomus/test'
      preLoaderRoute: typeof ApiNomusTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/propostas/$id/': {
      id: '/app/propostas/$id/'
      path: '/'
      fullPath: '/app/propostas/$id/'
      preLoaderRoute: typeof AppPropostasIdIndexRouteImport
      parentRoute: typeof AppPropostasIdRoute
    }
    '/app/configuracoes/templates/': {
      id: '/app/configuracoes/templates/'
      path: '/templates'
      fullPath: '/app/configuracoes/templates/'
      preLoaderRoute: typeof AppConfiguracoesTemplatesIndexRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/propostas/$id/editor': {
      id: '/app/propostas/$id/editor'
      path: '/editor'
      fullPath: '/app/propostas/$id/editor'
      preLoaderRoute: typeof AppPropostasIdEditorRouteImport
      parentRoute: typeof AppPropostasIdRoute
    }
    '/app/configuracoes/templates/$id': {
      id: '/app/configuracoes/templates/$id'
      path: '/templates/$id'
      fullPath: '/app/configuracoes/templates/$id'
      preLoaderRoute: typeof AppConfiguracoesTemplatesIdRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/configuracoes/nomus/importar-custos': {
      id: '/app/configuracoes/nomus/importar-custos'
      path: '/importar-custos'
      fullPath: '/app/configuracoes/nomus/importar-custos'
      preLoaderRoute: typeof AppConfiguracoesNomusImportarCustosRouteImport
      parentRoute: typeof AppConfiguracoesNomusRoute
    }
    '/api/public/nomus/tabela-preco-probe': {
      id: '/api/public/nomus/tabela-preco-probe'
      path: '/api/public/nomus/tabela-preco-probe'
      fullPath: '/api/public/nomus/tabela-preco-probe'
      preLoaderRoute: typeof ApiPublicNomusTabelaPrecoProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nomus/tabela-preco-deep-probe': {
      id: '/api/public/nomus/tabela-preco-deep-probe'
      path: '/api/public/nomus/tabela-preco-deep-probe'
      fullPath: '/api/public/nomus/tabela-preco-deep-probe'
      preLoaderRoute: typeof ApiPublicNomusTabelaPrecoDeepProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nomus/produto-probe': {
      id: '/api/public/nomus/produto-probe'
      path: '/api/public/nomus/produto-probe'
      fullPath: '/api/public/nomus/produto-probe'
      preLoaderRoute: typeof ApiPublicNomusProdutoProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nomus/exhaustive-probe': {
      id: '/api/public/nomus/exhaustive-probe'
      path: '/api/public/nomus/exhaustive-probe'
      fullPath: '/api/public/nomus/exhaustive-probe'
      preLoaderRoute: typeof ApiPublicNomusExhaustiveProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppConfiguracoesNomusRouteChildren {
  AppConfiguracoesNomusImportarCustosRoute: typeof AppConfiguracoesNomusImportarCustosRoute
}

const AppConfiguracoesNomusRouteChildren: AppConfiguracoesNomusRouteChildren = {
  AppConfiguracoesNomusImportarCustosRoute:
    AppConfiguracoesNomusImportarCustosRoute,
}

const AppConfiguracoesNomusRouteWithChildren =
  AppConfiguracoesNomusRoute._addFileChildren(
    AppConfiguracoesNomusRouteChildren,
  )

interface AppConfiguracoesRouteChildren {
  AppConfiguracoesApiNomusRoute: typeof AppConfiguracoesApiNomusRoute
  AppConfiguracoesNomusRoute: typeof AppConfiguracoesNomusRouteWithChildren
  AppConfiguracoesIndexRoute: typeof AppConfiguracoesIndexRoute
  AppConfiguracoesTemplatesIdRoute: typeof AppConfiguracoesTemplatesIdRoute
  AppConfiguracoesTemplatesIndexRoute: typeof AppConfiguracoesTemplatesIndexRoute
}

const AppConfiguracoesRouteChildren: AppConfiguracoesRouteChildren = {
  AppConfiguracoesApiNomusRoute: AppConfiguracoesApiNomusRoute,
  AppConfiguracoesNomusRoute: AppConfiguracoesNomusRouteWithChildren,
  AppConfiguracoesIndexRoute: AppConfiguracoesIndexRoute,
  AppConfiguracoesTemplatesIdRoute: AppConfiguracoesTemplatesIdRoute,
  AppConfiguracoesTemplatesIndexRoute: AppConfiguracoesTemplatesIndexRoute,
}

const AppConfiguracoesRouteWithChildren =
  AppConfiguracoesRoute._addFileChildren(AppConfiguracoesRouteChildren)

interface AppCrmRouteChildren {
  AppCrmIdRoute: typeof AppCrmIdRoute
}

const AppCrmRouteChildren: AppCrmRouteChildren = {
  AppCrmIdRoute: AppCrmIdRoute,
}

const AppCrmRouteWithChildren =
  AppCrmRoute._addFileChildren(AppCrmRouteChildren)

interface AppPropostasIdRouteChildren {
  AppPropostasIdEditorRoute: typeof AppPropostasIdEditorRoute
  AppPropostasIdIndexRoute: typeof AppPropostasIdIndexRoute
}

const AppPropostasIdRouteChildren: AppPropostasIdRouteChildren = {
  AppPropostasIdEditorRoute: AppPropostasIdEditorRoute,
  AppPropostasIdIndexRoute: AppPropostasIdIndexRoute,
}

const AppPropostasIdRouteWithChildren = AppPropostasIdRoute._addFileChildren(
  AppPropostasIdRouteChildren,
)

interface AppRouteChildren {
  AppAprovacoesRoute: typeof AppAprovacoesRoute
  AppClientesRoute: typeof AppClientesRoute
  AppCompetitivaRoute: typeof AppCompetitivaRoute
  AppConcorrentesRoute: typeof AppConcorrentesRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRouteWithChildren
  AppCrmRoute: typeof AppCrmRouteWithChildren
  AppDocumentosRoute: typeof AppDocumentosRoute
  AppEquipamentosRoute: typeof AppEquipamentosRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppSeletorRoute: typeof AppSeletorRoute
  AppTarefasRoute: typeof AppTarefasRoute
  AppIndexRoute: typeof AppIndexRoute
  AppColdproIdRoute: typeof AppColdproIdRoute
  AppColdproCatalogoRoute: typeof AppColdproCatalogoRoute
  AppPropostasIdRoute: typeof AppPropostasIdRouteWithChildren
  AppPropostasNovaRoute: typeof AppPropostasNovaRoute
  AppPropostasPedidosNfRoute: typeof AppPropostasPedidosNfRoute
  AppColdproIndexRoute: typeof AppColdproIndexRoute
  AppPropostasIndexRoute: typeof AppPropostasIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAprovacoesRoute: AppAprovacoesRoute,
  AppClientesRoute: AppClientesRoute,
  AppCompetitivaRoute: AppCompetitivaRoute,
  AppConcorrentesRoute: AppConcorrentesRoute,
  AppConfiguracoesRoute: AppConfiguracoesRouteWithChildren,
  AppCrmRoute: AppCrmRouteWithChildren,
  AppDocumentosRoute: AppDocumentosRoute,
  AppEquipamentosRoute: AppEquipamentosRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppSeletorRoute: AppSeletorRoute,
  AppTarefasRoute: AppTarefasRoute,
  AppIndexRoute: AppIndexRoute,
  AppColdproIdRoute: AppColdproIdRoute,
  AppColdproCatalogoRoute: AppColdproCatalogoRoute,
  AppPropostasIdRoute: AppPropostasIdRouteWithChildren,
  AppPropostasNovaRoute: AppPropostasNovaRoute,
  AppPropostasPedidosNfRoute: AppPropostasPedidosNfRoute,
  AppColdproIndexRoute: AppColdproIndexRoute,
  AppPropostasIndexRoute: AppPropostasIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  HooksNomusCronRoute: HooksNomusCronRoute,
  ApiNomusTestRoute: ApiNomusTestRoute,
  ApiPublicNomusExhaustiveProbeRoute: ApiPublicNomusExhaustiveProbeRoute,
  ApiPublicNomusProdutoProbeRoute: ApiPublicNomusProdutoProbeRoute,
  ApiPublicNomusTabelaPrecoDeepProbeRoute:
    ApiPublicNomusTabelaPrecoDeepProbeRoute,
  ApiPublicNomusTabelaPrecoProbeRoute: ApiPublicNomusTabelaPrecoProbeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
