ALTER TABLE public.coldpro_environment_products
ADD COLUMN IF NOT EXISTS specific_heat_above_kj_kg_k numeric,
ADD COLUMN IF NOT EXISTS specific_heat_below_kj_kg_k numeric,
ADD COLUMN IF NOT EXISTS latent_heat_kj_kg numeric,
ADD COLUMN IF NOT EXISTS water_content_percent numeric,
ADD COLUMN IF NOT EXISTS protein_content_percent numeric,
ADD COLUMN IF NOT EXISTS fat_content_percent numeric,
ADD COLUMN IF NOT EXISTS carbohydrate_content_percent numeric,
ADD COLUMN IF NOT EXISTS fiber_content_percent numeric,
ADD COLUMN IF NOT EXISTS ash_content_percent numeric,
ADD COLUMN IF NOT EXISTS respiration_rate_0c_mw_kg numeric,
ADD COLUMN IF NOT EXISTS respiration_rate_5c_mw_kg numeric,
ADD COLUMN IF NOT EXISTS respiration_rate_10c_mw_kg numeric,
ADD COLUMN IF NOT EXISTS respiration_rate_15c_mw_kg numeric,
ADD COLUMN IF NOT EXISTS respiration_rate_20c_mw_kg numeric,
ADD COLUMN IF NOT EXISTS notes text;

ALTER TABLE public.coldpro_tunnels
ADD COLUMN IF NOT EXISTS product_id uuid,
ADD COLUMN IF NOT EXISTS specific_heat_above_kj_kg_k numeric,
ADD COLUMN IF NOT EXISTS specific_heat_below_kj_kg_k numeric,
ADD COLUMN IF NOT EXISTS latent_heat_kj_kg numeric,
ADD COLUMN IF NOT EXISTS thermal_conductivity_unfrozen_w_m_k numeric,
ADD COLUMN IF NOT EXISTS water_content_percent numeric,
ADD COLUMN IF NOT EXISTS protein_content_percent numeric,
ADD COLUMN IF NOT EXISTS fat_content_percent numeric,
ADD COLUMN IF NOT EXISTS carbohydrate_content_percent numeric,
ADD COLUMN IF NOT EXISTS fiber_content_percent numeric,
ADD COLUMN IF NOT EXISTS ash_content_percent numeric,
ADD COLUMN IF NOT EXISTS frozen_water_fraction numeric,
ADD COLUMN IF NOT EXISTS freezable_water_content_percent numeric,
ADD COLUMN IF NOT EXISTS respiration_rate_0c_mw_kg numeric,
ADD COLUMN IF NOT EXISTS respiration_rate_5c_mw_kg numeric,
ADD COLUMN IF NOT EXISTS respiration_rate_10c_mw_kg numeric,
ADD COLUMN IF NOT EXISTS respiration_rate_15c_mw_kg numeric,
ADD COLUMN IF NOT EXISTS respiration_rate_20c_mw_kg numeric,
ADD COLUMN IF NOT EXISTS notes text;