ALTER TABLE public.coldpro_tunnels
ADD COLUMN IF NOT EXISTS tunnel_type TEXT,
ADD COLUMN IF NOT EXISTS arrangement_type TEXT,
ADD COLUMN IF NOT EXISTS product_geometry TEXT,
ADD COLUMN IF NOT EXISTS surface_exposure_model TEXT,
ADD COLUMN IF NOT EXISTS airflow_source TEXT DEFAULT 'manual_velocity',
ADD COLUMN IF NOT EXISTS fan_airflow_m3_h NUMERIC,
ADD COLUMN IF NOT EXISTS tunnel_cross_section_width_m NUMERIC,
ADD COLUMN IF NOT EXISTS tunnel_cross_section_height_m NUMERIC,
ADD COLUMN IF NOT EXISTS blockage_factor NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS calculated_air_velocity_m_s NUMERIC,
ADD COLUMN IF NOT EXISTS air_velocity_used_m_s NUMERIC,
ADD COLUMN IF NOT EXISTS gross_air_area_m2 NUMERIC,
ADD COLUMN IF NOT EXISTS free_air_area_m2 NUMERIC,
ADD COLUMN IF NOT EXISTS product_height_m NUMERIC,
ADD COLUMN IF NOT EXISTS product_side_m NUMERIC,
ADD COLUMN IF NOT EXISTS product_diameter_m NUMERIC,
ADD COLUMN IF NOT EXISTS equivalent_diameter_m NUMERIC,
ADD COLUMN IF NOT EXISTS characteristic_dimension_m NUMERIC,
ADD COLUMN IF NOT EXISTS box_length_m NUMERIC,
ADD COLUMN IF NOT EXISTS box_width_m NUMERIC,
ADD COLUMN IF NOT EXISTS box_height_m NUMERIC,
ADD COLUMN IF NOT EXISTS bulk_layer_height_m NUMERIC,
ADD COLUMN IF NOT EXISTS equivalent_particle_diameter_m NUMERIC;